set define off;

CREATE OR REPLACE procedure PRC_QGIS_COMPILA_INVALID_OBJ is
begin FOR cur IN (SELECT OBJECT_NAME, OBJECT_TYPE, owner
                  FROM   all_objects
                  WHERE  object_type  in ('JAVA RESOURCE','JAVA CLASS','JAVA SOURCE','PACKAGE','PACKAGE BODY','FUNCTION','PROCEDURE','VIEW',
                                          'SYNONYM')
                  and    owner        = 'SITIPIOPR'
                  AND    STATUS      != 'VALID'
                  and    OBJECT_NAME != 'PRC_QGIS_COMPILA_INVALID_OBJ') LOOP
BEGIN
  if cur.OBJECT_TYPE = 'PACKAGE BODY' then
    EXECUTE IMMEDIATE 'alter package "' || cur.owner || '"."' || cur.OBJECT_NAME || '" compile body';
  else
    EXECUTE IMMEDIATE 'alter ' || cur.OBJECT_TYPE || ' "' || cur.owner || '"."' || cur.OBJECT_NAME || '" compile';
  end if;
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
end loop;
end;
/


CREATE TABLE CATA_SEZIONI
(
  ID_COMUNE          NUMBER(9),
  ID_SEZIONE         NUMBER(9)                  NOT NULL,
  SEZIONE            VARCHAR2(10 BYTE)          NOT NULL,
  NOME               VARCHAR2(70 BYTE)          NOT NULL,
  INIZIO             DATE                       NOT NULL,
  FINE               DATE                       NOT NULL,
  COD_SEZIONE        VARCHAR2(10 BYTE),
  COD_TIPO_ZONA      NUMBER(1),
  FLAG_CATA          NUMBER(1)                  DEFAULT 0,
  CO_FOGLIO1         NUMBER(4)                  DEFAULT 1,
  CO_FOGLIO2         NUMBER(4)                  DEFAULT 0,
  CALCOLA_ANOM_TAVO  VARCHAR2(1 BYTE)           DEFAULT 'Y',
  NOME_INT           VARCHAR2(250 CHAR),
  PROJECTION_ID      NUMBER                     DEFAULT 0
)
TABLESPACE SITIPIOPR_tbl;

COMMENT ON TABLE CATA_SEZIONI IS 'sezioni di un comune';

COMMENT ON COLUMN CATA_SEZIONI.ID_COMUNE IS 'id univoco del comune di appartenenza';

COMMENT ON COLUMN CATA_SEZIONI.ID_SEZIONE IS 'id univoco della sezione (comu_seq)';

COMMENT ON COLUMN CATA_SEZIONI.SEZIONE IS 'sezione comunale';

COMMENT ON COLUMN CATA_SEZIONI.NOME IS 'nome sezione comunale';

COMMENT ON COLUMN CATA_SEZIONI.INIZIO IS 'data inizio validita';

COMMENT ON COLUMN CATA_SEZIONI.FINE IS 'data fine validita';

COMMENT ON COLUMN CATA_SEZIONI.CALCOLA_ANOM_TAVO IS 'CAMPO AGGIUNTO PER COMPATIBILITA CON CODAMMMNGR - NON USATO IN SIYIV1';


CREATE UNIQUE INDEX CATA_SEZIONI_COD ON CATA_SEZIONI
(COD_SEZIONE)
TABLESPACE SITIPIOPR_IDX;


CREATE INDEX CATA_SEZIONI_COM ON CATA_SEZIONI
(ID_COMUNE)
TABLESPACE SITIPIOPR_IDX;


CREATE UNIQUE INDEX CATA_SEZIONI_PK ON CATA_SEZIONI
(ID_SEZIONE)
TABLESPACE SITIPIOPR_IDX;


CREATE UNIQUE INDEX CATA_SEZIONI_UK ON CATA_SEZIONI
(ID_COMUNE, SEZIONE)
TABLESPACE SITIPIOPR_IDX;


CREATE INDEX TMP_CS_CS_IS ON CATA_SEZIONI
(COD_SEZIONE, ID_SEZIONE)
TABLESPACE SITIPIOPR_IDX;

CREATE TABLE CATA_COMU
(
  ID_COMUNE       NUMBER(9)                     NOT NULL,
  COD_COMUNE      VARCHAR2(10 BYTE)             NOT NULL,
  NOME            VARCHAR2(70 BYTE)             NOT NULL,
  INIZIO          DATE                          NOT NULL,
  FINE            DATE                          NOT NULL,
  ID_PROV         NUMBER(9),
  ISTATC          VARCHAR2(3 BYTE)              NOT NULL,
  DATA_IMPIANTO   DATE,
  TO_SYNC         NUMBER                        DEFAULT 2                     NOT NULL,
  NOME_INT        VARCHAR2(250 CHAR),
  ID_SERVER_SYNC  NUMBER(9)
)
TABLESPACE SITIPIOPR_TBL;

COMMENT ON TABLE CATA_COMU IS 'elenco dei comuni';

COMMENT ON COLUMN CATA_COMU.ID_COMUNE IS 'id univoco del comune (comu_seq)';

COMMENT ON COLUMN CATA_COMU.COD_COMUNE IS 'codice del comune';

COMMENT ON COLUMN CATA_COMU.NOME IS 'nome del comune';

COMMENT ON COLUMN CATA_COMU.INIZIO IS 'data inizio validita';

COMMENT ON COLUMN CATA_COMU.FINE IS 'data fine validita';

COMMENT ON COLUMN CATA_COMU.DATA_IMPIANTO IS 'DATA DI IMPIANTO';

COMMENT ON COLUMN CATA_COMU.TO_SYNC IS '0 NON SYNC; 1 SYNC PARZIALE; 2 SYNC ALL';

COMMENT ON COLUMN CATA_COMU.ID_SERVER_SYNC IS 'ADDRESS ID OF SERVER SYNC';



CREATE INDEX CATA_COMU_IX1 ON CATA_COMU
(ID_PROV, ID_COMUNE)
TABLESPACE SITIPIOPR_IDX;


CREATE UNIQUE INDEX CATA_COMU_PK ON CATA_COMU
(ID_COMUNE)
TABLESPACE SITIPIOPR_IDX;


CREATE INDEX CATA_COMU_UK1 ON CATA_COMU
(COD_COMUNE)
TABLESPACE SITIPIOPR_IDX;


CREATE INDEX TMP_CATACOMU_ISTAT_IDPROV ON CATA_COMU
(ISTATC, ID_PROV)
TABLESPACE SITIPIOPR_IDX;


CREATE INDEX TMP_CATCOM_ISTATC ON CATA_COMU
(ISTATC)
TABLESPACE SITIPIOPR_IDX;


CREATE INDEX TMP_CTCOM_IP_IC ON CATA_COMU
(ID_COMUNE, ID_PROV)
TABLESPACE SITIPIOPR_IDX;

CREATE TABLE CATA_PROV
(
  ID_PROV        NUMBER(9)                      NOT NULL,
  ID_REGI        NUMBER(9),
  DENO_PROV      VARCHAR2(70 BYTE)              NOT NULL,
  SIGLA_PROV     VARCHAR2(2 BYTE)               NOT NULL,
  ISTATP         VARCHAR2(3 BYTE)               NOT NULL,
  INIZIO         DATE                           DEFAULT SYSDATE               NOT NULL,
  FINE           DATE                           DEFAULT SYSDATE               NOT NULL,
  DENO_PROV_INT  VARCHAR2(250 CHAR),
  COORD_SYS      VARCHAR2(1024 CHAR)
)
TABLESPACE SITIPIOPR_TBL;


CREATE UNIQUE INDEX CATA_PROV_PK ON CATA_PROV
(ID_PROV)
TABLESPACE SITIPIOPR_IDX;


CREATE UNIQUE INDEX CATA_PROV_UK ON CATA_PROV
(ID_REGI, ISTATP)
TABLESPACE SITIPIOPR_IDX;


CREATE INDEX TMP_CATPRO_ISTATP ON CATA_PROV
(ISTATP)
TABLESPACE SITIPIOPR_IDX;


ALTER TABLE CATA_PROV ADD (
  CONSTRAINT CATA_PROV_PK
  PRIMARY KEY
  (ID_PROV)
  USING INDEX CATA_PROV_PK
  ENABLE VALIDATE);
  
CREATE TABLE CATA_REGI
(
  ID_REGI        NUMBER(9)                      NOT NULL,
  DENO_REGI      VARCHAR2(70 BYTE)              NOT NULL,
  ISTATR         VARCHAR2(3 BYTE)               NOT NULL,
  INIZIO         DATE                           DEFAULT SYSDATE               NOT NULL,
  FINE           DATE                           DEFAULT SYSDATE               NOT NULL,
  DENO_REGI_INT  VARCHAR2(250 CHAR)
)
TABLESPACE SITIPIOPR_TBL;


CREATE UNIQUE INDEX CATA_REGI_PK ON CATA_REGI
(ID_REGI)
TABLESPACE SITIPIOPR_IDX;


CREATE UNIQUE INDEX CATA_REGI_UK ON CATA_REGI
(ISTATR)
TABLESPACE SITIPIOPR_IDX;


ALTER TABLE CATA_REGI ADD (
  CONSTRAINT CATA_REGI_PK
  PRIMARY KEY
  (ID_REGI)
  USING INDEX CATA_REGI_PK
  ENABLE VALIDATE);  

CREATE SEQUENCE SEQ_QGIS_T_EVENTO_LAVORAZIONE
	START WITH 1
	NOCACHE;

CREATE SEQUENCE SEQ_QGIS_T_LISTA_LAVORAZIONE
	START WITH 1
	NOCACHE;

CREATE SEQUENCE SEQ_QGIS_T_PARTICELLA_LAVORAZI
	START WITH 1
	NOCACHE;

CREATE SEQUENCE SEQ_QGIS_T_SUOLO_BLOCCATO
	START WITH 1
	NOCACHE;

CREATE SEQUENCE SEQ_QGIS_T_SUOLO_LAVORAZIONE
	START WITH 1
	NOCACHE;

CREATE SEQUENCE SEQ_QGIS_T_SUOLO_PARTICELLA
	START WITH 1
	NOCACHE;

CREATE SEQUENCE SEQ_QGIS_T_SUOLO_PROPOSTO
	START WITH 1
	NOCACHE;

CREATE SEQUENCE SEQ_QGIS_T_SUOLO_RILEVATO
	START WITH 1
	NOCACHE;

CREATE SEQUENCE SEQ_QGIS_T_VERSIONE_PARTICELLA
	START WITH 1
	NOCACHE;

CREATE TABLE QGIS_D_TIPO_LISTA
(
	ID_TIPO_LISTA        NUMBER(4) NOT NULL ,
	DESCRIZIONE          VARCHAR2(200) NOT NULL 
)
	TABLESPACE SITIPIOPR_TBL;

COMMENT ON TABLE QGIS_D_TIPO_LISTA IS 'In base al tipo la lista permette lavorazioni su Suoli Rilevati, Particelle o entrambi';

CREATE UNIQUE INDEX PK_QGIS_D_TIPO_LISTA ON QGIS_D_TIPO_LISTA
(ID_TIPO_LISTA   ASC)
	TABLESPACE SITIPIOPR_IDX;

ALTER TABLE QGIS_D_TIPO_LISTA
	ADD CONSTRAINT  PK_QGIS_D_TIPO_LISTA PRIMARY KEY (ID_TIPO_LISTA);

CREATE TABLE QGIS_D_TIPO_SORGENTE_SUOLO
(
	ID_TIPO_SORGENTE_SUOLO NUMBER(4) NOT NULL ,
	DESCRIZIONE          VARCHAR2(200) NOT NULL 
)
	TABLESPACE SITIPIOPR_TBL;

COMMENT ON TABLE QGIS_D_TIPO_SORGENTE_SUOLO IS 'Indica se il suolo deriva da una lavorazione in contraddittorio o da sopralluogo, etc';

CREATE UNIQUE INDEX PK_QGIS_D_TIPO_SORGENTE_SUOLO ON QGIS_D_TIPO_SORGENTE_SUOLO
(ID_TIPO_SORGENTE_SUOLO   ASC)
	TABLESPACE SITIPIOPR_IDX;

ALTER TABLE QGIS_D_TIPO_SORGENTE_SUOLO
	ADD CONSTRAINT  PK_QGIS_D_TIPO_SORGENTE_SUOLO PRIMARY KEY (ID_TIPO_SORGENTE_SUOLO);

CREATE TABLE QGIS_T_EVENTO_LAVORAZIONE
(
	ID_EVENTO_LAVORAZIONE NUMBER(10) NOT NULL ,
	ID_LISTA_LAVORAZIONE NUMBER(10) NOT NULL ,
	DATA_LAVORAZIONE     DATE NULL ,
	DATA_INSERIMENTO     DATE NOT NULL ,
	EXT_ID_AZIENDA       NUMBER(10) NULL ,
	EXT_ID_UTENTE_INSERIMENTO NUMBER(10) NOT NULL ,
	EXT_ID_UTENTE_LAVORAZIONE NUMBER(10) NULL 
)
	TABLESPACE SITIPIOPR_TBL;

CREATE UNIQUE INDEX PK_QGIS_T_EVENTO_LAVORAZIONE ON QGIS_T_EVENTO_LAVORAZIONE
(ID_EVENTO_LAVORAZIONE   ASC)
	TABLESPACE SITIPIOPR_IDX;

ALTER TABLE QGIS_T_EVENTO_LAVORAZIONE
	ADD CONSTRAINT  PK_QGIS_T_EVENTO_LAVORAZIONE PRIMARY KEY (ID_EVENTO_LAVORAZIONE);

CREATE TABLE QGIS_T_LISTA_LAVORAZIONE
(
	ID_LISTA_LAVORAZIONE NUMBER(10) NOT NULL ,
	ID_TIPO_LISTA        NUMBER(4) NOT NULL ,
	CAMPAGNA             NUMBER(4) NOT NULL ,
	CODICE               VARCHAR2(20) NOT NULL ,
	DESCRIZIONE_LISTA    VARCHAR2(200) NOT NULL 
)
	TABLESPACE SITIPIOPR_TBL;

CREATE UNIQUE INDEX PK_QGIS_T_LISTA_LAVORAZIONE ON QGIS_T_LISTA_LAVORAZIONE
(ID_LISTA_LAVORAZIONE   ASC)
	TABLESPACE SITIPIOPR_IDX;

ALTER TABLE QGIS_T_LISTA_LAVORAZIONE
	ADD CONSTRAINT  PK_QGIS_T_LISTA_LAVORAZIONE PRIMARY KEY (ID_LISTA_LAVORAZIONE);

CREATE TABLE QGIS_T_PARTICELLA_LAVORAZIONE
(
	ID_PARTICELLA_LAVORAZIONE NUMBER(10) NOT NULL ,
	ID_EVENTO_LAVORAZIONE NUMBER(10) NOT NULL ,
	ID_VERSIONE_PARTICELLA NUMBER(10) NOT NULL ,
	DESCRIZIONE_SOSPENSIONE VARCHAR2(200) NOT NULL ,
	FLAG_SOSPENSIONE     VARCHAR2(1) NOT NULL  CONSTRAINT  CK_FLAG_01 CHECK (FLAG_SOSPENSIONE IN ('S','N')),
	FLAG_CESSATO         VARCHAR2(1) NOT NULL  CONSTRAINT  CK_FLAG_02 CHECK (FLAG_CESSATO IN ('S','N'))
)
	TABLESPACE SITIPIOPR_TBL;

CREATE UNIQUE INDEX PK_QGIS_T_PARTICELLA_LAVORAZIO ON QGIS_T_PARTICELLA_LAVORAZIONE
(ID_PARTICELLA_LAVORAZIONE   ASC)
	TABLESPACE SITIPIOPR_IDX;

ALTER TABLE QGIS_T_PARTICELLA_LAVORAZIONE
	ADD CONSTRAINT  PK_QGIS_T_PARTICELLA_LAVORAZIO PRIMARY KEY (ID_PARTICELLA_LAVORAZIONE);

CREATE TABLE QGIS_T_SUOLO_BLOCCATO
(
	ID_SUOLO_BLOCCATO    NUMBER(10) NOT NULL ,
	ID_EVENTO_LAVORAZIONE NUMBER(10) NOT NULL ,
	ID_SUOLO_RILEVATO    NUMBER(10) NOT NULL ,
	DATA_INIZIO_BLOCCO   DATE NOT NULL ,
	DATA_FINE_BLOCCO     DATE NULL ,
	EXT_ID_UTENTE_BLOCCO NUMBER(10) NOT NULL 
)
	TABLESPACE SITIPIOPR_TBL;

CREATE UNIQUE INDEX PK_QGIS_T_SUOLO_BLOCCATO ON QGIS_T_SUOLO_BLOCCATO
(ID_SUOLO_BLOCCATO   ASC)
	TABLESPACE SITIPIOPR_IDX;

ALTER TABLE QGIS_T_SUOLO_BLOCCATO
	ADD CONSTRAINT  PK_QGIS_T_SUOLO_BLOCCATO PRIMARY KEY (ID_SUOLO_BLOCCATO);

CREATE TABLE QGIS_T_SUOLO_LAVORAZIONE
(
	ID_SUOLO_LAVORAZIONE NUMBER(10) NOT NULL ,
	ID_EVENTO_LAVORAZIONE NUMBER(10) NOT NULL ,
	ID_SUOLO_RILEVATO    NUMBER(10) NOT NULL ,
	DESCRIZIONE_SOSPENSIONE VARCHAR2(200) NULL ,
	FLAG_SOSPENSIONE     VARCHAR2(1) NOT NULL  CONSTRAINT  CK_FLAG_03 CHECK (FLAG_SOSPENSIONE IN ('S','N')),
	FLAG_CESSATO         VARCHAR2(1) NOT NULL  CONSTRAINT  CK_FLAG_04 CHECK (FLAG_CESSATO IN ('S','N'))
)
	TABLESPACE SITIPIOPR_TBL;

CREATE UNIQUE INDEX PK_QGIS_T_SUOLO_LAVORAZIONE ON QGIS_T_SUOLO_LAVORAZIONE
(ID_SUOLO_LAVORAZIONE   ASC)
	TABLESPACE SITIPIOPR_IDX;

ALTER TABLE QGIS_T_SUOLO_LAVORAZIONE
	ADD CONSTRAINT  PK_QGIS_T_SUOLO_LAVORAZIONE PRIMARY KEY (ID_SUOLO_LAVORAZIONE);

CREATE TABLE QGIS_T_SUOLO_PARTICELLA
(
	ID_SUOLO_PARTICELLA  NUMBER(10) NOT NULL ,
	ID_SUOLO_RILEVATO    NUMBER(10) NOT NULL ,
	ID_VERSIONE_PARTICELLA NUMBER(10) NOT NULL ,
	AREA                 NUMBER(11,2) NOT NULL ,
	DATA_AGGIORNAMENTO   DATE NOT NULL ,
	PROG_POLIGONO        NUMBER(5) NOT NULL ,
	SHAPE                SDO_Geometry NOT NULL ,
	EXT_ID_UTENTE_AGGIORNAMENTO NUMBER(10) NOT NULL 
)
COLUMN SHAPE NOT SUBSTITUTABLE AT ALL LEVELS
VARRAY "SHAPE"."SDO_ELEM_INFO" STORE AS LOB (tablespace SITIPIOPR_lob)
VARRAY "SHAPE"."SDO_ORDINATES" STORE AS LOB (tablespace SITIPIOPR_lob)
	TABLESPACE SITIPIOPR_TBL;

CREATE UNIQUE INDEX PK_QGIS_T_SUOLO_PARTICELLA ON QGIS_T_SUOLO_PARTICELLA
(ID_SUOLO_PARTICELLA   ASC)
	TABLESPACE SITIPIOPR_IDX;

ALTER TABLE QGIS_T_SUOLO_PARTICELLA
	ADD CONSTRAINT  PK_QGIS_T_SUOLO_PARTICELLA PRIMARY KEY (ID_SUOLO_PARTICELLA);

CREATE TABLE QGIS_T_SUOLO_PROPOSTO
(
	ID_SUOLO_PROPOSTO    NUMBER(10) NOT NULL ,
	ID_EVENTO_LAVORAZIONE NUMBER(10) NOT NULL ,
	EXT_ID_ELEGGIBILITA_RILEVATA NUMBER(8) NOT NULL ,
	EXT_ID_ISTA_RIES     NUMBER NULL ,
	SHAPE                SDO_Geometry NOT NULL 
)
COLUMN SHAPE NOT SUBSTITUTABLE AT ALL LEVELS
VARRAY "SHAPE"."SDO_ELEM_INFO" STORE AS LOB (tablespace SITIPIOPR_lob)
VARRAY "SHAPE"."SDO_ORDINATES" STORE AS LOB (tablespace SITIPIOPR_lob)
	TABLESPACE SITIPIOPR_TBL;

COMMENT ON COLUMN QGIS_T_SUOLO_PROPOSTO.EXT_ID_ISTA_RIES IS 'punta alla tabella di anagrafe AABGISTA_RIES_TAB';

CREATE UNIQUE INDEX PK_QGIS_T_SUOLO_PROPOSTO ON QGIS_T_SUOLO_PROPOSTO
(ID_SUOLO_PROPOSTO   ASC)
	TABLESPACE SITIPIOPR_IDX;

ALTER TABLE QGIS_T_SUOLO_PROPOSTO
	ADD CONSTRAINT  PK_QGIS_T_SUOLO_PROPOSTO PRIMARY KEY (ID_SUOLO_PROPOSTO);

CREATE TABLE QGIS_T_SUOLO_RILEVATO
(
	ID_SUOLO_RILEVATO    NUMBER(10) NOT NULL ,
	AREA                 NUMBER(11,2) NOT NULL ,
	CAMPAGNA             NUMBER(4) NOT NULL ,
	EXT_COD_NAZIONALE    VARCHAR2(10) NOT NULL ,
	FOGLIO               NUMBER(4) NOT NULL ,
	DATA_INIZIO_VALIDITA DATE NOT NULL ,
	DATA_FINE_VALIDITA   DATE NULL ,
	DATA_AGGIORNAMENTO   DATE NOT NULL ,
	EXT_ID_ELEGGIBILITA_RILEVATA NUMBER(8) NOT NULL ,
	EXT_ID_UTENTE_AGGIORNAMENTO NUMBER(10) NOT NULL ,
	ID_TIPO_SORGENTE_SUOLO NUMBER(4) NOT NULL ,
	SHAPE                SDO_Geometry NOT NULL 
)
COLUMN SHAPE NOT SUBSTITUTABLE AT ALL LEVELS
VARRAY "SHAPE"."SDO_ELEM_INFO" STORE AS LOB (tablespace SITIPIOPR_lob)
VARRAY "SHAPE"."SDO_ORDINATES" STORE AS LOB (tablespace SITIPIOPR_lob)
	TABLESPACE SITIPIOPR_TBL;

COMMENT ON COLUMN QGIS_T_SUOLO_RILEVATO.EXT_COD_NAZIONALE IS 'punta alla tabella di anagrafe DB_SITICOMU';

CREATE UNIQUE INDEX PK_QGIS_T_SUOLO_RILEVATO ON QGIS_T_SUOLO_RILEVATO
(ID_SUOLO_RILEVATO   ASC)
	TABLESPACE SITIPIOPR_IDX;

ALTER TABLE QGIS_T_SUOLO_RILEVATO
	ADD CONSTRAINT  PK_QGIS_T_SUOLO_RILEVATO PRIMARY KEY (ID_SUOLO_RILEVATO);

CREATE TABLE QGIS_T_VERSIONE_PARTICELLA
(
	ID_VERSIONE_PARTICELLA NUMBER(10) NOT NULL ,
	EXT_ID_PARTICELLA    NUMBER(10) NOT NULL ,
	EXT_COD_NAZIONALE    VARCHAR2(10) NOT NULL ,
	FOGLIO               NUMBER(4) NOT NULL ,
	PARTICELLA           VARCHAR2(5) NOT NULL ,
	SUBALTERNO           VARCHAR2(3) NOT NULL,
	DATA_INIZIO_VALIDITA DATE NOT NULL ,
	DATA_FINE_VALIDITA   DATE NULL ,
	AREA                 NUMBER(11,2) NOT NULL ,
	SHAPE                SDO_Geometry NOT NULL ,
	DATA_AGGIORNAMENTO   DATE NOT NULL ,
	EXT_ID_UTENTE_AGGIORNAMENTO NUMBER(10) NOT NULL
)
COLUMN SHAPE NOT SUBSTITUTABLE AT ALL LEVELS
VARRAY "SHAPE"."SDO_ELEM_INFO" STORE AS LOB (tablespace SITIPIOPR_lob)
VARRAY "SHAPE"."SDO_ORDINATES" STORE AS LOB (tablespace SITIPIOPR_lob)
	TABLESPACE SITIPIOPR_TBL;

COMMENT ON COLUMN QGIS_T_VERSIONE_PARTICELLA.EXT_COD_NAZIONALE IS 'punta alla tabella di anagrafe DB_SITICOMU';

CREATE UNIQUE INDEX PK_QGIS_T_VERSIONE_PARTICELLA ON QGIS_T_VERSIONE_PARTICELLA
(ID_VERSIONE_PARTICELLA   ASC)
	TABLESPACE SITIPIOPR_IDX;

ALTER TABLE QGIS_T_VERSIONE_PARTICELLA
	ADD CONSTRAINT  PK_QGIS_T_VERSIONE_PARTICELLA PRIMARY KEY (ID_VERSIONE_PARTICELLA);

ALTER TABLE QGIS_T_EVENTO_LAVORAZIONE
	ADD (CONSTRAINT FK_QGIS_T_LISTA_LAVORAZIONE_01 FOREIGN KEY (ID_LISTA_LAVORAZIONE) REFERENCES QGIS_T_LISTA_LAVORAZIONE (ID_LISTA_LAVORAZIONE));

ALTER TABLE QGIS_T_LISTA_LAVORAZIONE
	ADD (CONSTRAINT FK_QGIS_D_TIPO_LISTA_01 FOREIGN KEY (ID_TIPO_LISTA) REFERENCES QGIS_D_TIPO_LISTA (ID_TIPO_LISTA));

ALTER TABLE QGIS_T_PARTICELLA_LAVORAZIONE
	ADD (CONSTRAINT FK_QGIS_T_EVENTO_LAVORAZION_01 FOREIGN KEY (ID_EVENTO_LAVORAZIONE) REFERENCES QGIS_T_EVENTO_LAVORAZIONE (ID_EVENTO_LAVORAZIONE));

ALTER TABLE QGIS_T_PARTICELLA_LAVORAZIONE
	ADD (CONSTRAINT FK_QGIS_T_VERSIONE_PARTICEL_01 FOREIGN KEY (ID_VERSIONE_PARTICELLA) REFERENCES QGIS_T_VERSIONE_PARTICELLA (ID_VERSIONE_PARTICELLA));

ALTER TABLE QGIS_T_SUOLO_BLOCCATO
	ADD (CONSTRAINT FK_QGIS_T_EVENTO_LAVORAZION_04 FOREIGN KEY (ID_EVENTO_LAVORAZIONE) REFERENCES QGIS_T_EVENTO_LAVORAZIONE (ID_EVENTO_LAVORAZIONE));

ALTER TABLE QGIS_T_SUOLO_BLOCCATO
	ADD (CONSTRAINT FK_QGIS_T_SUOLO_RILEVATO_03 FOREIGN KEY (ID_SUOLO_RILEVATO) REFERENCES QGIS_T_SUOLO_RILEVATO (ID_SUOLO_RILEVATO));

ALTER TABLE QGIS_T_SUOLO_LAVORAZIONE
	ADD (CONSTRAINT FK_QGIS_T_EVENTO_LAVORAZION_02 FOREIGN KEY (ID_EVENTO_LAVORAZIONE) REFERENCES QGIS_T_EVENTO_LAVORAZIONE (ID_EVENTO_LAVORAZIONE));

ALTER TABLE QGIS_T_SUOLO_LAVORAZIONE
	ADD (CONSTRAINT FK_QGIS_T_SUOLO_RILEVATO_02 FOREIGN KEY (ID_SUOLO_RILEVATO) REFERENCES QGIS_T_SUOLO_RILEVATO (ID_SUOLO_RILEVATO));

ALTER TABLE QGIS_T_SUOLO_PARTICELLA
	ADD (CONSTRAINT FK_QGIS_T_SUOLO_RILEVATO_01 FOREIGN KEY (ID_SUOLO_RILEVATO) REFERENCES QGIS_T_SUOLO_RILEVATO (ID_SUOLO_RILEVATO));

ALTER TABLE QGIS_T_SUOLO_PARTICELLA
	ADD (CONSTRAINT FK_QGIS_T_VERSIONE_PARTICEL_02 FOREIGN KEY (ID_VERSIONE_PARTICELLA) REFERENCES QGIS_T_VERSIONE_PARTICELLA (ID_VERSIONE_PARTICELLA));

ALTER TABLE QGIS_T_SUOLO_PROPOSTO
	ADD (CONSTRAINT FK_QGIS_T_EVENTO_LAVORAZION_03 FOREIGN KEY (ID_EVENTO_LAVORAZIONE) REFERENCES QGIS_T_EVENTO_LAVORAZIONE (ID_EVENTO_LAVORAZIONE));

ALTER TABLE QGIS_T_SUOLO_RILEVATO
	ADD (CONSTRAINT FK_QGIS_D_TIPO_SORGENTE_SUO_01 FOREIGN KEY (ID_TIPO_SORGENTE_SUOLO) REFERENCES QGIS_D_TIPO_SORGENTE_SUOLO (ID_TIPO_SORGENTE_SUOLO));

INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
VALUES(
	'QGIS_T_SUOLO_PARTICELLA', 
	'SHAPE',
	SDO_DIM_ARRAY(
		SDO_DIM_ELEMENT ('X', 1310000, 2820000, 0.005),
		SDO_DIM_ELEMENT ('Y', 3930000, 5220000, 0.005)
	),
	NULL
);

INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
VALUES(
	'QGIS_T_SUOLO_PROPOSTO', 
	'SHAPE',
	SDO_DIM_ARRAY(
		SDO_DIM_ELEMENT ('X', 1310000, 2820000, 0.005),
		SDO_DIM_ELEMENT ('Y', 3930000, 5220000, 0.005)
	),
	NULL
);

INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
VALUES(
	'QGIS_T_SUOLO_RILEVATO', 
	'SHAPE',
	SDO_DIM_ARRAY(
		SDO_DIM_ELEMENT ('X', 1310000, 2820000, 0.005),
		SDO_DIM_ELEMENT ('Y', 3930000, 5220000, 0.005)
	),
	NULL
);

INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
VALUES(
	'QGIS_T_VERSIONE_PARTICELLA', 
	'SHAPE',
	SDO_DIM_ARRAY(
		SDO_DIM_ELEMENT ('X', 1310000, 2820000, 0.005),
		SDO_DIM_ELEMENT ('Y', 3930000, 5220000, 0.005)
	),
	NULL
);

COMMIT;

ALTER TABLE QGIS_T_EVENTO_LAVORAZIONE MODIFY(EXT_ID_UTENTE_INSERIMENTO NUMBER(10) NULL);

ALTER TABLE QGIS_T_VERSIONE_PARTICELLA MODIFY(EXT_ID_UTENTE_AGGIORNAMENTO NUMBER(10) NULL);

ALTER TABLE QGIS_T_SUOLO_RILEVATO MODIFY(EXT_ID_UTENTE_AGGIORNAMENTO NUMBER(10) NULL);

ALTER TABLE QGIS_T_SUOLO_PARTICELLA MODIFY(EXT_ID_UTENTE_AGGIORNAMENTO NUMBER(10) NULL);

ALTER TABLE QGIS_T_EVENTO_LAVORAZIONE
	ADD (EXT_ID_UTENTE_INSER_SITICLIENT varchar2(100));

ALTER TABLE QGIS_T_EVENTO_LAVORAZIONE
	ADD (EXT_ID_UTENTE_LAVOR_SITICLIENT varchar2(100));

ALTER TABLE QGIS_T_VERSIONE_PARTICELLA
	ADD (EXT_ID_UTENTE_LAVOR_SITICLIENT NUMBER(10));

ALTER TABLE QGIS_T_SUOLO_RILEVATO
	ADD (EXT_ID_UTENTE_LAVOR_SITICLIENT NUMBER(10));

ALTER TABLE QGIS_T_SUOLO_PARTICELLA
	ADD (EXT_ID_UTENTE_LAVOR_SITICLIENT NUMBER(10));   

ALTER TABLE QGIS_T_VERSIONE_PARTICELLA MODIFY(EXT_ID_PARTICELLA NUMBER(10) NULL);   

ALTER TABLE QGIS_T_PARTICELLA_LAVORAZIONE MODIFY ID_VERSIONE_PARTICELLA NULL;

CREATE INDEX IE1_QGIS_T_VERSIONE_PARTICELLA ON QGIS_T_VERSIONE_PARTICELLA
(EXT_ID_PARTICELLA   ASC)
    TABLESPACE SITIPIOPR_IDX;
	
CREATE SEQUENCE SEQ_QGIS_T_VARIAZIONE_CATASTAL
	START WITH 1
	NOCACHE;

ALTER TABLE QGIS_T_LISTA_LAVORAZIONE
	ADD (ID_TIPO_SORGENTE_SUOLO NUMBER(4));

ALTER TABLE QGIS_T_PARTICELLA_LAVORAZIONE
	ADD (NOTE_RICHIESTA VARCHAR2(4000));

ALTER TABLE QGIS_T_PARTICELLA_LAVORAZIONE
	ADD (NOTE_LAVORAZIONE VARCHAR2(4000));

ALTER TABLE QGIS_T_SUOLO_RILEVATO
	ADD (NOTE_RICHIESTA VARCHAR2(4000));

ALTER TABLE QGIS_T_SUOLO_RILEVATO
	ADD (NOTE_LAVORAZIONE VARCHAR2(4000));

CREATE TABLE QGIS_T_VARIAZIONE_CATASTALE
(
	ID_VARIAZIONE_CATASTALE NUMBER(10) NOT NULL ,
	ID_VERSIONE_PARTICELLA_PADRE NUMBER(10) NOT NULL ,
	ID_VERSIONE_PARTICELLA_FIGLIO NUMBER(10) NOT NULL ,
	DATA_VARIAZIONE      DATE NOT NULL 
)
	TABLESPACE SITIPIOPR_TBL;

CREATE UNIQUE INDEX PK_QGIS_T_VARIAZIONE_CATASTALE ON QGIS_T_VARIAZIONE_CATASTALE
(ID_VARIAZIONE_CATASTALE   ASC)
	TABLESPACE SITIPIOPR_IDX;

ALTER TABLE QGIS_T_VARIAZIONE_CATASTALE
ADD CONSTRAINT  PK_QGIS_T_VARIAZIONE_CATASTALE PRIMARY KEY (ID_VARIAZIONE_CATASTALE);

ALTER TABLE QGIS_T_VARIAZIONE_CATASTALE
ADD CONSTRAINT FK_QGIS_T_VERSIONE_PARTICEL_03 FOREIGN KEY (ID_VERSIONE_PARTICELLA_PADRE) REFERENCES QGIS_T_VERSIONE_PARTICELLA (ID_VERSIONE_PARTICELLA);

ALTER TABLE QGIS_T_VARIAZIONE_CATASTALE
ADD CONSTRAINT FK_QGIS_T_VERSIONE_PARTICEL_04 FOREIGN KEY (ID_VERSIONE_PARTICELLA_FIGLIO) REFERENCES QGIS_T_VERSIONE_PARTICELLA (ID_VERSIONE_PARTICELLA);

ALTER TABLE QGIS_T_LISTA_LAVORAZIONE
ADD CONSTRAINT FK_QGIS_D_TIPO_SORGENTE_SUO_02 FOREIGN KEY (ID_TIPO_SORGENTE_SUOLO) REFERENCES QGIS_D_TIPO_SORGENTE_SUOLO (ID_TIPO_SORGENTE_SUOLO);

Insert into QGIS_D_TIPO_LISTA
   (ID_TIPO_LISTA, DESCRIZIONE)
 Values
   (1, 'Lavorazione Particelle');
Insert into QGIS_D_TIPO_LISTA
   (ID_TIPO_LISTA, DESCRIZIONE)
 Values
   (2, 'Lavorazione Suoli');
COMMIT;

Insert into QGIS_D_TIPO_SORGENTE_SUOLO
   (ID_TIPO_SORGENTE_SUOLO, DESCRIZIONE)
 Values
   (1, 'FOTO-INTERPRETAZIONE');
Insert into QGIS_D_TIPO_SORGENTE_SUOLO
   (ID_TIPO_SORGENTE_SUOLO, DESCRIZIONE)
 Values
   (2, 'CONTRADDITTORIO');
Insert into QGIS_D_TIPO_SORGENTE_SUOLO
   (ID_TIPO_SORGENTE_SUOLO, DESCRIZIONE)
 Values
   (3, 'SOPRALLUOGO');
Insert into QGIS_D_TIPO_SORGENTE_SUOLO
   (ID_TIPO_SORGENTE_SUOLO, DESCRIZIONE)
 Values
   (4, 'CONTROLLO OGGETTIVO');
Insert into QGIS_D_TIPO_SORGENTE_SUOLO
   (ID_TIPO_SORGENTE_SUOLO, DESCRIZIONE)
 Values
   (5, 'CONTROLLO OGGETTIVO CAMPO');
COMMIT;

CREATE SEQUENCE SEQ_QGIS_T_VARIAZION_SUOLO_RIL
	START WITH 1
	NOCACHE;

ALTER TABLE QGIS_T_SUOLO_PROPOSTO
	ADD (EXT_COD_NAZIONALE VARCHAR2(4) NOT NULL);

ALTER TABLE QGIS_T_SUOLO_PROPOSTO
	ADD (FOGLIO NUMBER(4) NOT NULL);

CREATE TABLE QGIS_T_VARIAZIONE_SUOLO_RIL
(
	ID_VARIAZIONE_SUOLO_RIL NUMBER(10) NOT NULL ,
	ID_SUOLO_RILEVATO_PADRE NUMBER(10) NOT NULL ,
	ID_SUOLO_RILEVATO_FIGLIO NUMBER(10) NOT NULL ,
	DATA_VARIAZIONE      DATE NOT NULL 
)
	TABLESPACE SITIPIOPR_TBL;

CREATE UNIQUE INDEX PK_QGIS_T_VARIAZIONE_SUOLO_RIL ON QGIS_T_VARIAZIONE_SUOLO_RIL
(ID_VARIAZIONE_SUOLO_RIL   ASC)
	TABLESPACE SITIPIOPR_IDX;

ALTER TABLE QGIS_T_VARIAZIONE_SUOLO_RIL
ADD CONSTRAINT  PK_QGIS_T_VARIAZIONE_SUOLO_RIL PRIMARY KEY (ID_VARIAZIONE_SUOLO_RIL);

ALTER TABLE QGIS_T_VARIAZIONE_SUOLO_RIL
ADD CONSTRAINT FK_QGIS_T_SUOLO_RILEVATO_04 FOREIGN KEY (ID_SUOLO_RILEVATO_PADRE) REFERENCES QGIS_T_SUOLO_RILEVATO (ID_SUOLO_RILEVATO);

ALTER TABLE QGIS_T_VARIAZIONE_SUOLO_RIL
ADD CONSTRAINT FK_QGIS_T_SUOLO_RILEVATO_05 FOREIGN KEY (ID_SUOLO_RILEVATO_FIGLIO) REFERENCES QGIS_T_SUOLO_RILEVATO (ID_SUOLO_RILEVATO);

ALTER TABLE QGIS_T_SUOLO_LAVORAZIONE
	ADD (NOTE_RICHIESTA VARCHAR2(4000));

ALTER TABLE QGIS_T_SUOLO_LAVORAZIONE
	ADD (NOTE_LAVORAZIONE VARCHAR2(4000));
	
ALTER TABLE QGIS_T_SUOLO_RILEVATO
  DROP COLUMN NOTE_RICHIESTA CASCADE CONSTRAINTS;

ALTER TABLE QGIS_T_SUOLO_RILEVATO
  DROP COLUMN NOTE_LAVORAZIONE CASCADE CONSTRAINTS;	
  
CREATE INDEX IE2_QGIS_T_SUOLO_LAVORAZIONE ON QGIS_T_SUOLO_LAVORAZIONE
(ID_EVENTO_LAVORAZIONE)
TABLESPACE SITIPIOPR_IDX;

CREATE INDEX IE2_QGIS_T_SUOLO_PROPOSTO ON QGIS_T_SUOLO_PROPOSTO
(ID_EVENTO_LAVORAZIONE)
TABLESPACE SITIPIOPR_IDX;

CREATE INDEX IE2_QGIS_T_EVENTO_LAVORAZIONE ON QGIS_T_EVENTO_LAVORAZIONE
(ID_LISTA_LAVORAZIONE)
TABLESPACE SITIPIOPR_IDX;

CREATE INDEX IE1_QGIS_T_SUOLO_BLOCCATO ON QGIS_T_SUOLO_BLOCCATO
(ID_EVENTO_LAVORAZIONE)
TABLESPACE SITIPIOPR_IDX;

CREATE TABLE QGIS_D_TIPO_MOTIVO_SOSPENSIONE
(
	ID_TIPO_MOTIVO_SOSPENSIONE NUMBER(4) NOT NULL ,
	DESC_TIPO_MOTIVO_SOSPENSIONE VARCHAR2(200) NOT NULL ,
	DATA_INIZIO_VALIDITA DATE NOT NULL ,
	DATA_FINE_VALIDITA   DATE NULL 
)
	TABLESPACE SITIPIOPR_TBL;

CREATE UNIQUE INDEX PK_QGIS_D_TIPO_MOTIVO_SOSPENSI ON QGIS_D_TIPO_MOTIVO_SOSPENSIONE
(ID_TIPO_MOTIVO_SOSPENSIONE   ASC)
	TABLESPACE SITIPIOPR_IDX;

ALTER TABLE QGIS_D_TIPO_MOTIVO_SOSPENSIONE
ADD CONSTRAINT  PK_QGIS_D_TIPO_MOTIVO_SOSPENSI PRIMARY KEY (ID_TIPO_MOTIVO_SOSPENSIONE);

ALTER TABLE QGIS_T_VERSIONE_PARTICELLA
	ADD (flag_Geom_Corrotta VARCHAR2(1)  DEFAULT 'N' NOT NULL CONSTRAINT CK_FLAG_06 CHECK (flag_Geom_Corrotta IN ('S','N')));

ALTER TABLE QGIS_T_SUOLO_RILEVATO
	ADD (flag_Geom_Corrotta VARCHAR2(1)  DEFAULT 'N' NOT NULL CONSTRAINT CK_FLAG_05 CHECK (flag_Geom_Corrotta IN ('S','N')));

CREATE OR REPLACE TYPE obj_Suoli_In_Lavorazione AS object(
id_Feature NUMBER(10),
Geometria_WKT CLOB,
codice_Nazionale VARCHaR2(10),
Foglio NUMBER(4),
Id_Eleggibilita_Rilevata NUMBER(8),
codice_Eleggibilita_Rilevata VARCHaR2(4),
note VARCHaR2(4000),
Tipo_Suolo VARCHaR2(20));
/

CREATE OR REPLACE TYPE  list_Suoli_In_Lavorazione AS TABLE OF obj_Suoli_In_Lavorazione ;
/

ALTER TABLE QGIS_T_SUOLO_LAVORAZIONE
	ADD (ID_TIPO_MOTIVO_SOSPENSIONE NUMBER(4));

ALTER TABLE QGIS_T_SUOLO_LAVORAZIONE
ADD CONSTRAINT FK_QGIS_D_TIPO_MOTIVO_SOSPE_01 FOREIGN KEY (ID_TIPO_MOTIVO_SOSPENSIONE) REFERENCES QGIS_D_TIPO_MOTIVO_SOSPENSIONE (ID_TIPO_MOTIVO_SOSPENSIONE);

create or replace synonym PAPUA_V_UTENTE_LOGIN for papua.PAPUA_V_UTENTE_LOGIN ;

drop table QGIS_T_SUOLO_BLOCCATO cascade constraints;

ALTER TABLE QGIS_T_PARTICELLA_LAVORAZIONE
	ADD (Flag_Lavorato VARCHAR2(1)  DEFAULT 'N' NOT NULL CONSTRAINT CK_FLAG_08 CHECK (Flag_Lavorato IN ('S','N')));

ALTER TABLE QGIS_T_SUOLO_LAVORAZIONE
	ADD (Flag_Lavorato VARCHAR2(1)  DEFAULT 'N' NOT NULL CONSTRAINT CK_FLAG_07 CHECK (Flag_Lavorato IN ('S','N')));	
	
CREATE SEQUENCE SEQ_QGIS_T_EVENTO_BLOCCATO
	START WITH 1
	NOCACHE;

CREATE SEQUENCE SEQ_QGIS_T_FOGLIO_BLOCCATO
	START WITH 1
	NOCACHE;

CREATE TABLE QGIS_T_EVENTO_BLOCCATO
(
	ID_EVENTO_BLOCCATO   NUMBER(10) NOT NULL ,
	ID_EVENTO_LAVORAZIONE NUMBER(10) NOT NULL ,
	DATA_INIZIO_VALIDITA DATE NOT NULL ,
	DATA_FINE_VALIDITA   DATE NULL ,
	EXT_ID_UTENTE_AGGIORNAMENTO NUMBER(10) NULL 
)
	TABLESPACE SITIPIOPR_TBL;

CREATE UNIQUE INDEX PK_QGIS_T_EVENTO_BLOCCATO ON QGIS_T_EVENTO_BLOCCATO
(ID_EVENTO_BLOCCATO   ASC)
	TABLESPACE SITIPIOPR_IDX;

CREATE TABLE QGIS_T_FOGLIO_BLOCCATO
(
	ID_FOGLIO_BLOCCATO   NUMBER(10) NOT NULL ,
	ID_EVENTO_BLOCCATO   NUMBER(10) NOT NULL ,
	EXT_COD_NAZIONALE    VARCHAR2(10) NOT NULL ,
	FOGLIO               NUMBER(4) NOT NULL ,
	DATA_INIZIO_VALIDITA DATE NOT NULL ,
	DATA_FINE_VALIDITA   DATE NULL ,
	EXT_ID_UTENTE_AGGIORNAMENTO NUMBER(10) NULL 
)
	TABLESPACE SITIPIOPR_TBL;

COMMENT ON COLUMN QGIS_T_FOGLIO_BLOCCATO.EXT_COD_NAZIONALE IS 'punta alla tabella di anagrafe DB_SITICOMU';

CREATE UNIQUE INDEX PK_QGIS_T_FOGLIO_BLOCCATO ON QGIS_T_FOGLIO_BLOCCATO
(ID_FOGLIO_BLOCCATO   ASC)
	TABLESPACE SITIPIOPR_IDX;

ALTER TABLE QGIS_T_EVENTO_BLOCCATO
ADD CONSTRAINT  PK_QGIS_T_EVENTO_BLOCCATO PRIMARY KEY (ID_EVENTO_BLOCCATO);

ALTER TABLE QGIS_T_FOGLIO_BLOCCATO
ADD CONSTRAINT  PK_QGIS_T_FOGLIO_BLOCCATO PRIMARY KEY (ID_FOGLIO_BLOCCATO);

ALTER TABLE QGIS_T_EVENTO_BLOCCATO
ADD CONSTRAINT FK_QGIS_T_EVENTO_LAVORAZION_04 FOREIGN KEY (ID_EVENTO_LAVORAZIONE) REFERENCES QGIS_T_EVENTO_LAVORAZIONE (ID_EVENTO_LAVORAZIONE);

ALTER TABLE QGIS_T_FOGLIO_BLOCCATO
ADD CONSTRAINT FK_QGIS_T_EVENTO_BLOCCATO_01 FOREIGN KEY (ID_EVENTO_BLOCCATO) REFERENCES QGIS_T_EVENTO_BLOCCATO (ID_EVENTO_BLOCCATO);

drop SEQUENCE SEQ_QGIS_T_SUOLO_BLOCCATO;

ALTER TABLE QGIS_T_SUOLO_LAVORAZIONE
	ADD (Tipo_Suolo_Origine VARCHAR2(20));
	
CREATE INDEX IE3_QGIS_T_VERSIONE_PARTICELLA ON QGIS_T_VERSIONE_PARTICELLA
(EXT_COD_NAZIONALE, DATA_INIZIO_VALIDITA, FOGLIO, PARTICELLA, SUBALTERNO, 
EXT_ID_PARTICELLA)
TABLESPACE SITIPIOPR_IDX;	

CREATE INDEX IE2_QGIS_T_SUOLO_PARTICELLA ON QGIS_T_SUOLO_PARTICELLA
(ID_SUOLO_RILEVATO) PARALLEL
TABLESPACE SITIPIOPR_IDX;

CREATE INDEX IE3_QGIS_T_SUOLO_PARTICELLA ON QGIS_T_SUOLO_PARTICELLA
(ID_VERSIONE_PARTICELLA) PARALLEL
TABLESPACE SITIPIOPR_IDX;

CREATE INDEX IE1_QGIS_T_EVENTO_LAVORAZIONE ON QGIS_T_EVENTO_LAVORAZIONE
(EXT_ID_AZIENDA)
TABLESPACE SITIPIOPR_IDX;

CREATE INDEX IE1_QGIS_T_PARTICELLA_LAVORAZI ON QGIS_T_PARTICELLA_LAVORAZIONE
(ID_EVENTO_LAVORAZIONE)
TABLESPACE SITIPIOPR_IDX;

alter table QGIS_T_SUOLO_PARTICELLA modify EXT_ID_UTENTE_LAVOR_SITICLIENT varchar2(100);
alter table QGIS_T_SUOLO_RILEVATO modify  EXT_ID_UTENTE_LAVOR_SITICLIENT varchar2(100);
alter table QGIS_T_VERSIONE_PARTICELLA modify  EXT_ID_UTENTE_LAVOR_SITICLIENT varchar2(100);

ALTER TABLE QGIS_T_SUOLO_PROPOSTO
	ADD (IDENTIFICATIVO_PRATICA_ORIGINE VARCHAR2(50));

COMMENT ON COLUMN QGIS_T_SUOLO_PROPOSTO.IDENTIFICATIVO_PRATICA_ORIGINE IS 'Indica l''identificativo della pratica di origine che puo'' legare diversi documenti archiviati';


ALTER TABLE QGIS_T_SUOLO_LAVORAZIONE
	ADD (IDENTIFICATIVO_PRATICA_ORIGINE VARCHAR2(50));

COMMENT ON COLUMN QGIS_T_SUOLO_LAVORAZIONE.IDENTIFICATIVO_PRATICA_ORIGINE IS 'Indica l''identificativo della pratica di origine che puo'' legare diversi documenti archiviati';

CREATE SEQUENCE SEQ_QGIS_W_GESTIONE_COOKIE START WITH 1 NOCACHE;

CREATE TABLE QGIS_W_GESTIONE_COOKIE 
    ( 
     ID_GESTIONE_COOKIE NUMBER (10)  NOT NULL , 
     COOKIE_1           VARCHAR2 (4000)  NOT NULL , 
     COOKIE_2           VARCHAR2 (4000)  NOT NULL , 
     COOKIE_3           VARCHAR2 (4000) , 
     COOKIE_4           VARCHAR2 (4000) , 
     COOKIE_5           VARCHAR2 (4000) 
    ) 
    TABLESPACE SITIPIOPR_TBL 
;
CREATE UNIQUE INDEX PK_QGIS_W_GESTIONE_COOKIE ON QGIS_W_GESTIONE_COOKIE 
    ( 
     ID_GESTIONE_COOKIE ASC 
    ) 
    TABLESPACE SITIPIOPR_IDX 
;

ALTER TABLE QGIS_W_GESTIONE_COOKIE 
    ADD CONSTRAINT PK_QGIS_W_GESTIONE_COOKIE PRIMARY KEY ( ID_GESTIONE_COOKIE ) ;

create sequence SEQ_QGIS_T_FOGLIO_RIFERIMENTO START WITH 1 NOCACHE;
	
CREATE TABLE QGIS_T_FOGLIO_RIFERIMENTO 
    ( 
     ID_FOGLIO_RIFERIMENTO NUMBER (10)  NOT NULL , 
     ID_GEO_FOGLIO         NUMBER , 
     COD_COM_BELFIORE      VARCHAR2 (4) , 
     COD_COM_ISTAT         VARCHAR2 (6) , 
     COMUNE                VARCHAR2 (80) , 
     SEZIONE               VARCHAR2 (1) , 
     FOGLIO                VARCHAR2 (10) , 
     ALLEGATO              VARCHAR2 (1) , 
     SVILUPPO              VARCHAR2 (1) , 
     AGGIORNATO_AL         DATE , 
     STATO                 VARCHAR2 (20) , 
     COD_COM_ISTAT_BDTRE   VARCHAR2 (6) , 
     EXT_COD_NAZIONALE     VARCHAR2 (4) , 
     DATA_INIZIO_VALIDITA  DATE  NOT NULL , 
     DATA_FINE_VALIDITA    DATE , 
     SHAPE                 SDO_GEOMETRY  NOT NULL , 
     Campagna_Inizio NUMBER (4)  NOT NULL , 
     Campagna_Fine NUMBER (4)  NOT NULL 
    ) 
 COLUMN SHAPE NOT SUBSTITUTABLE AT ALL LEVELS
VARRAY "SHAPE"."SDO_ELEM_INFO" STORE AS LOB (tablespace SITIPIOPR_lob)
VARRAY "SHAPE"."SDO_ORDINATES" STORE AS LOB (tablespace SITIPIOPR_lob)
	TABLESPACE SITIPIOPR_TBL;
	

CREATE UNIQUE INDEX PK_QGIS_T_FOGLIO_RIFERIMENTO ON QGIS_T_FOGLIO_RIFERIMENTO 
    ( 
     ID_FOGLIO_RIFERIMENTO ASC 
    ) 
    TABLESPACE SITIPIOPR_IDX 
;

ALTER TABLE QGIS_T_FOGLIO_RIFERIMENTO 
    ADD CONSTRAINT PK_QGIS_T_FOGLIO_RIFERIMENTO PRIMARY KEY ( ID_FOGLIO_RIFERIMENTO ) ;	
	
INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
VALUES(
	'QGIS_T_FOGLIO_RIFERIMENTO', 
	'SHAPE',
	SDO_DIM_ARRAY(
		SDO_DIM_ELEMENT ('X', 1310000, 2820000, 0.005),
		SDO_DIM_ELEMENT ('Y', 3930000, 5220000, 0.005)
	),
	NULL
);

COMMIT;

CREATE INDEX IE1_QGIS_T_FOGLIO_RIFERIMENTO ON QGIS_T_FOGLIO_RIFERIMENTO(SHAPE)
   INDEXTYPE IS MDSYS.SPATIAL_INDEX PARALLEL
   PARAMETERS('tablespace=SITIPIOPR_IDX');		
   
CREATE TABLE QGIS_D_PARAMETRO_PLUGIN 
    ( 
     ID_PARAMETRO_PLUGIN  NUMBER (4)  NOT NULL , 
     Codice               VARCHAR2 (20)  NOT NULL , 
     descrizione          VARCHAR2 (4000)  NOT NULL , 
     Tipo                 VARCHAR2 (1)  NOT NULL , 
     Valore_Stringa       VARCHAR2 (1000) , 
     Valore_Numerico      NUMBER , 
     Valore_Data          DATE , 
     Data_Inizio_Validita DATE  NOT NULL , 
     Data_Fine_Validita   DATE 
    ) 
    TABLESPACE SITIPIOPR_TBL 
;

CREATE UNIQUE INDEX PK_QGIS_D_PARAMETRO_PLUGIN ON QGIS_D_PARAMETRO_PLUGIN 
    ( 
     ID_PARAMETRO_PLUGIN ASC 
    ) 
    TABLESPACE SITIPIOPR_IDX 
;

ALTER TABLE QGIS_D_PARAMETRO_PLUGIN 
    ADD CONSTRAINT PK_QGIS_D_PARAMETRO_PLUGIN PRIMARY KEY ( ID_PARAMETRO_PLUGIN ) ;   
	
ALTER TABLE QGIS_W_GESTIONE_COOKIE ADD 
    ( 
     PARAMETRO VARCHAR2 (4000) 
    ) 
;	

CREATE SEQUENCE SEQ_QGIS_T_SUOLO_UNAR START WITH 1 NOCACHE;

CREATE TABLE QGIS_T_SUOLO_UNAR 
    ( 
     ID_SUOLO_UNAR        NUMBER (10)  NOT NULL , 
     ID_SUOLO_RILEVATO    NUMBER (10)  NOT NULL , 
     EXT_ID_UNITA_ARBOREA NUMBER (10)  NOT NULL , 
     DATA_INIZIO_VALIDITA DATE  NOT NULL , 
     DATA_FINE_VALIDITA   DATE 
    ) 
TABLESPACE SITIPIOPR_TBL;


COMMENT ON TABLE QGIS_T_SUOLO_UNAR IS 'tabella per il collegamento tra UNAR e Suoli Rilevati' 
;

ALTER TABLE QGIS_T_SUOLO_UNAR 
    ADD CONSTRAINT PK_QGIS_T_SUOLO_UNAR PRIMARY KEY ( ID_SUOLO_UNAR  ) USING INDEX TABLESPACE SITIPIOPR_IDX;


ALTER TABLE QGIS_T_SUOLO_UNAR 
    ADD CONSTRAINT FK_QGIS_T_SUOLO_RILEVATO_06 FOREIGN KEY 
    ( 
     ID_SUOLO_RILEVATO
    ) 
    REFERENCES QGIS_T_SUOLO_RILEVATO 
    ( 
     ID_SUOLO_RILEVATO
    ) 
;

GRANT SELECT,INSERT,DELETE,UPDATE ON QGIS_T_SUOLO_UNAR TO SMRGAA,SMRGAA_RW;
GRANT SELECT ON SEQ_QGIS_T_SUOLO_UNAR TO SMRGAA,SMRGAA_RW;

Insert into QGIS_D_PARAMETRO_PLUGIN
   (ID_PARAMETRO_PLUGIN, CODICE, DESCRIZIONE, TIPO, VALORE_NUMERICO, 
    DATA_INIZIO_VALIDITA, DATA_FINE_VALIDITA)
 Values
   (1, 'ANNO_IMP_SUOLO', 'Anno da cui importate tutte le fotointerpretazioni usato in PCK_SITI_SVECCHIA', 'N', 2015, 
    TO_DATE('09/24/2020 11:29:09', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('09/24/2020 11:29:11', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;

alter type OBJ_SUOLI_IN_LAVORAZIONE add attribute srid number cascade;

CREATE SEQUENCE SEQ_QGIS_L_LOG_BATCH		  START WITH 1 NOCACHE;
CREATE SEQUENCE SEQ_QGIS_L_PROCESSO_BATCH  START WITH 1 NOCACHE;

CREATE TABLE QGIS_D_ERRORE_BATCH 
    ( 
     CODICE_ERRORE VARCHAR2 (10 BYTE)  NOT NULL , 
     DESC_ERRORE   VARCHAR2 (100 BYTE)  NOT NULL 
    ) 
TABLESPACE SITIPIOPR_TBL;

CREATE UNIQUE INDEX PK_QGIS_D_ERRORE_BATCH ON QGIS_D_ERRORE_BATCH 
    ( 
    CODICE_ERRORE ASC 
    ) 
TABLESPACE SITIPIOPR_IDX;

ALTER TABLE QGIS_D_ERRORE_BATCH 
    ADD CONSTRAINT PK_QGIS_D_ERRORE_BATCH PRIMARY KEY ( CODICE_ERRORE  ) 
    USING INDEX TABLESPACE SITIPIOPR_IDX;

CREATE TABLE QGIS_D_NOME_BATCH 
    ( 
     ID_NOME_BATCH        NUMBER (3)  NOT NULL , 
     NOME_BATCH           VARCHAR2 (300 BYTE)  NOT NULL , 
     DESC_BATCH           VARCHAR2 (100 BYTE)  NOT NULL , 
     NOME_JOBSET          VARCHAR2 (20 BYTE) , 
     DT_ULTIMA_ESECUZIONE DATE 
    ) 
TABLESPACE SITIPIOPR_TBL;


ALTER TABLE QGIS_D_NOME_BATCH 
    ADD CONSTRAINT PK_QGIS_D_NOME_BATCH PRIMARY KEY ( ID_NOME_BATCH  ) 
    USING INDEX TABLESPACE SITIPIOPR_IDX;

CREATE TABLE QGIS_L_LOG_BATCH 
    ( 
     ID_LOG_BATCH      NUMBER  NOT NULL , 
     ID_PROCESSO_BATCH NUMBER  NOT NULL , 
     DT_INSERIMENTO    DATE  NOT NULL , 
     MESSAGGIO_ERRORE  VARCHAR2 (4000 BYTE) , 
     CODICE_ERRORE     VARCHAR2 (10 BYTE)  NOT NULL 
    ) 
TABLESPACE SITIPIOPR_TBL;


ALTER TABLE QGIS_L_LOG_BATCH 
    ADD CONSTRAINT PK_QGIS_L_LOG_BATCH PRIMARY KEY ( ID_LOG_BATCH  ) 
    USING INDEX TABLESPACE SITIPIOPR_IDX;

CREATE TABLE QGIS_L_PROCESSO_BATCH 
    ( 
     ID_PROCESSO_BATCH      NUMBER  NOT NULL , 
     ID_NOME_BATCH          NUMBER (3)  NOT NULL , 
     DT_INIZIO_ELABORAZIONE DATE  NOT NULL , 
     DT_FINE_ELABORAZIONE   DATE , 
     FLAG_ESITO             VARCHAR2 (2 BYTE) 
    ) 
TABLESPACE SITIPIOPR_TBL;


ALTER TABLE QGIS_L_PROCESSO_BATCH 
    ADD CONSTRAINT PK_QGIS_L_PROCESSO_BATCH PRIMARY KEY ( ID_PROCESSO_BATCH  ) 
    USING INDEX TABLESPACE SITIPIOPR_IDX;



ALTER TABLE QGIS_L_LOG_BATCH 
    ADD CONSTRAINT FK_QGIS_D_ERRORE_BATCH_01 FOREIGN KEY 
    ( 
     CODICE_ERRORE
    ) 
    REFERENCES QGIS_D_ERRORE_BATCH 
    ( 
     CODICE_ERRORE
    );


ALTER TABLE QGIS_L_LOG_BATCH 
    ADD CONSTRAINT FK_QGIS_L_PROCE_BATCH_01 FOREIGN KEY 
    ( 
     ID_PROCESSO_BATCH
    ) 
    REFERENCES QGIS_L_PROCESSO_BATCH 
    ( 
     ID_PROCESSO_BATCH
    );


ALTER TABLE QGIS_L_PROCESSO_BATCH 
    ADD CONSTRAINT FK_QGIS_D_NOME_BATCH_01 FOREIGN KEY 
    ( 
     ID_NOME_BATCH
    ) 
    REFERENCES QGIS_D_NOME_BATCH 
    ( 
     ID_NOME_BATCH
    );

	
CREATE TABLE QGIS_W_SITIPART
(
  COD_NAZIONALE       CHAR(4 BYTE)              NOT NULL,
  FOGLIO              NUMBER(4)                 NOT NULL,
  PARTICELLA          CHAR(5 BYTE)              NOT NULL,
  SUB                 VARCHAR2(3 BYTE)          NOT NULL,
  DATA_LAV            DATE                      DEFAULT SYSDATE               NOT NULL,
  ALLEGATO            CHAR(1 BYTE)              DEFAULT '0'                   NOT NULL,
  SVILUPPO            CHAR(1 BYTE)              DEFAULT '0'                   NOT NULL,
  UTENTE              VARCHAR2(100 BYTE)        NOT NULL,
  DATA_INIZIO_VAL     DATE                      NOT NULL,
  DATA_FINE_VAL       DATE                      NOT NULL,
  SHAPE               MDSYS.SDO_GEOMETRY,
  AREA_PART           NUMBER(11,2),
  DELTA_X_FOTO        NUMBER(5,2),
  DELTA_Y_FOTO        NUMBER(5,2),
  CONTRASTO           NUMBER(3),
  LUMINOSITA          NUMBER(3),
  COD_DIGI            NUMBER(2),
  COD_EDIF            NUMBER(2),
  FLAG1               CHAR(3 BYTE),
  FLAG2               CHAR(3 BYTE),
  FLAG3               CHAR(3 BYTE),
  SE_ROW_ID           NUMBER(10)                NOT NULL,
  NOTE                VARCHAR2(255 BYTE),
  ISTATP              NUMBER(3),
  STATO_PROP          NUMBER(1)                 DEFAULT 0,
  UTENTE_FINE         VARCHAR2(100 BYTE),
  UTENTE_PROP         VARCHAR2(100 BYTE),
  UTENTE_PROP_FINE    VARCHAR2(100 BYTE),
  ID_TRASF            NUMBER(9)                 DEFAULT 0,
  ID_TRASF_FINE       NUMBER(9)                 DEFAULT 0,
  SORGENTE            NUMBER(9),
  VALI_PROD           NUMBER(1),
  TAVOLA              NUMBER(4),
  FLAGCARICO          NUMBER(9),
  DATA_AGGIORNAMENTO  DATE,
  ID_PARTICELLA       NUMBER(9),
  ID_CATA_PART        NUMBER(9),
  ALMOST_DEAD         NUMBER,
  FLAG_PROVENIENZA    VARCHAR2(1 BYTE),
  SYNC_SV_ID          NUMBER(9)
)
COLUMN SHAPE NOT SUBSTITUTABLE AT ALL LEVELS
VARRAY "SHAPE"."SDO_ELEM_INFO" STORE AS LOB (tablespace SITIPIOPR_lob)
VARRAY "SHAPE"."SDO_ORDINATES" STORE AS LOB (tablespace SITIPIOPR_lob)
TABLESPACE SITIPIOPR_TBL;

CREATE TABLE SITISUOLO_ATTIVE
(
  SE_ROW_ID             NUMBER(10)              NOT NULL,
  ISTAT_COMUNE          CHAR(6 BYTE)            NOT NULL,
  SEZIONE               VARCHAR2(1 BYTE),
  COD_NAZIONALE         VARCHAR2(4 BYTE)        NOT NULL,
  FOGLIO                NUMBER(4)               NOT NULL,
  PARTICELLA            VARCHAR2(5 BYTE)        NOT NULL,
  SUB                   VARCHAR2(3 BYTE)        NOT NULL,
  CAMPAGNA              NUMBER(4)               NOT NULL,
  PROG_POLIGONO         NUMBER(5)               NOT NULL,
  DATA_AGGIORNAMENTO    DATE                    NOT NULL,
  COD_VARIETA           NUMBER(5)               NOT NULL,
  DATA_INIZIO_VALIDITA  DATE                    NOT NULL,
  DATA_FINE_VALIDITA    DATE                    NOT NULL,
  SHAPE                 MDSYS.SDO_GEOMETRY,
  ID_PARTICELLA         NUMBER(9),
  AREA_COLT             NUMBER(11,2),
  UTENTE                VARCHAR2(100 BYTE),
  SORGENTE              NUMBER(9)
)
COLUMN SHAPE NOT SUBSTITUTABLE AT ALL LEVELS
VARRAY "SHAPE"."SDO_ELEM_INFO" STORE AS LOB (tablespace SITIPIOPR_lob)
VARRAY "SHAPE"."SDO_ORDINATES" STORE AS LOB (tablespace SITIPIOPR_lob)
TABLESPACE SITIPIOPR_TBL
;

CREATE OR REPLACE FORCE VIEW SITICOMU
(
   COD_NAZIONALE,
   ISTATP,
   ISTATC,
   ID_SEZC,
   NOME,
   DENO_PROV,
   SIGLA_PROV,
   ISTATR,
   CODI_FISC_LUNA,
   FLAG_CATA,
   CO_FOGLIO1,
   CO_FOGLIO2,
   COD_PROVINCIA,
   COD_COMUNE,
   SEZIONE_CENSUARIA,
   COD_TIPO_ZONA,
   ISOPR,
   DATA_AGGIORNAMENTO,
   CODICE_TNBZ,
   ID_COMUNE,
   ID_SEZIONE,
   ID_PROV,
   NOME_INT,
   DENO_PROV_INT,
   NOME_COMUNE,
   NOME_COMUNE_INT,
   DENO_REGI,
   DENO_REGI_INT
)
AS
   (SELECT d.cod_sezione,
           b.istatp,
           c.istatc,
           TRIM (d.sezione),
           d.nome,
           b.deno_prov,
           b.sigla_prov,
           a.istatr,
           c.cod_comune,
           d.flag_cata,
           d.co_foglio1,
           d.co_foglio2,
           TO_NUMBER (b.istatp),
           TO_NUMBER (c.istatc),
           d.sezione,
           d.cod_tipo_zona,
           NULL AS isopr,
           d.inizio AS data_aggiornamento,
           NULL AS codice_tnbz,
           c.id_comune,
           d.id_sezione,
           b.id_prov,
           d.nome_int,
           b.deno_prov_int,
           c.nome,
           c.nome_int,
           a.deno_regi,
           a.deno_regi_int
      FROM cata_regi a,
           cata_prov b,
           cata_comu c,
           cata_sezioni d
     WHERE     b.id_regi = a.id_regi
           AND c.id_prov = b.id_prov
           AND d.id_comune = c.id_comune);
		   
CREATE TABLE TMP_ROCCO
(
  COL1  VARCHAR2(4000 BYTE),
  COL2  DATE                                    DEFAULT sysdate
)
TABLESPACE SITIPIOPR_TBL;		 

CREATE INDEX IE_SITISUOLO_ATTIVE_01 ON SITISUOLO_ATTIVE (COD_NAZIONALE, FOGLIO, PARTICELLA, CAMPAGNA, DATA_INIZIO_VALIDITA) TABLESPACE SITIPIOPR_IDX; 

CREATE TABLE SITIPART_ATTIVE
(
  COD_NAZIONALE       CHAR(4 BYTE)              NOT NULL,
  FOGLIO              NUMBER(4)                 NOT NULL,
  PARTICELLA          CHAR(5 BYTE)              NOT NULL,
  SUB                 VARCHAR2(3 BYTE)          NOT NULL,
  DATA_LAV            DATE                      DEFAULT SYSDATE               NOT NULL,
  ALLEGATO            CHAR(1 BYTE)              DEFAULT '0'                   NOT NULL,
  SVILUPPO            CHAR(1 BYTE)              DEFAULT '0'                   NOT NULL,
  UTENTE              VARCHAR2(100 BYTE)        NOT NULL,
  DATA_INIZIO_VAL     DATE                      NOT NULL,
  DATA_FINE_VAL       DATE                      NOT NULL,
  SHAPE               MDSYS.SDO_GEOMETRY,
  AREA_PART           NUMBER(11,2),
  DELTA_X_FOTO        NUMBER(5,2),
  DELTA_Y_FOTO        NUMBER(5,2),
  CONTRASTO           NUMBER(3),
  LUMINOSITA          NUMBER(3),
  COD_DIGI            NUMBER(2),
  COD_EDIF            NUMBER(2),
  FLAG1               CHAR(3 BYTE),
  FLAG2               CHAR(3 BYTE),
  FLAG3               CHAR(3 BYTE),
  SE_ROW_ID           NUMBER(10)                NOT NULL,
  NOTE                VARCHAR2(255 BYTE),
  ISTATP              NUMBER(3),
  STATO_PROP          NUMBER(1)                 DEFAULT 0,
  UTENTE_FINE         VARCHAR2(100 BYTE),
  UTENTE_PROP         VARCHAR2(100 BYTE),
  UTENTE_PROP_FINE    VARCHAR2(100 BYTE),
  ID_TRASF            NUMBER(9)                 DEFAULT 0,
  ID_TRASF_FINE       NUMBER(9)                 DEFAULT 0,
  SORGENTE            NUMBER(9),
  VALI_PROD           NUMBER(1),
  TAVOLA              NUMBER(4),
  FLAGCARICO          NUMBER(9),
  DATA_AGGIORNAMENTO  DATE,
  ID_PARTICELLA       NUMBER(9),
  ID_CATA_PART        NUMBER(9),
  ALMOST_DEAD         NUMBER,
  FLAG_PROVENIENZA    VARCHAR2(1 BYTE),
  SYNC_SV_ID          NUMBER(9),
  EXT_ID_PARTICELLA   NUMBER(10)
)
COLUMN SHAPE NOT SUBSTITUTABLE AT ALL LEVELS
VARRAY "SHAPE"."SDO_ELEM_INFO" STORE AS LOB (tablespace SITIPIOPR_lob)
VARRAY "SHAPE"."SDO_ORDINATES" STORE AS LOB (tablespace SITIPIOPR_lob)
TABLESPACE SITIPIOPR_TBL;

CREATE TABLE SITICENT_ATTIVE
(
  COD_NAZIONALE       CHAR(4 BYTE)              NOT NULL,
  FOGLIO              NUMBER(4)                 NOT NULL,
  PARTICELLA          CHAR(5 BYTE)              NOT NULL,
  SUB                 VARCHAR2(3 BYTE)          NOT NULL,
  DATA_LAV            DATE                      DEFAULT SYSDATE               NOT NULL,
  ALLEGATO            CHAR(1 BYTE)              DEFAULT '0'                   NOT NULL,
  SVILUPPO            CHAR(1 BYTE)              DEFAULT '0'                   NOT NULL,
  UTENTE              VARCHAR2(100 BYTE)        NOT NULL,
  DATA_INIZIO_VAL     DATE,
  DATA_FINE_VAL       DATE                      NOT NULL,
  FLAG_FONTE_DATO     VARCHAR2(1 BYTE),
  CODI_FORN           VARCHAR2(1 BYTE),
  SHAPE               MDSYS.SDO_GEOMETRY,
  SE_ROW_ID           NUMBER(10)                NOT NULL,
  ISTATP              NUMBER(3),
  STATO_PROP          NUMBER(1)                 DEFAULT 0,
  UTENTE_FINE         VARCHAR2(100 BYTE),
  UTENTE_PROP         VARCHAR2(100 BYTE),
  UTENTE_PROP_FINE    VARCHAR2(100 BYTE),
  ID_TRASF            NUMBER(9)                 DEFAULT 0,
  ID_TRASF_FINE       NUMBER(9)                 DEFAULT 0,
  SORGENTE            NUMBER(9),
  VALI_PROD           NUMBER(1),
  TAVOLA              NUMBER(4),
  FLAGCARICO          NUMBER(9),
  DATA_AGGIORNAMENTO  DATE,
  ID_PARTICELLA       NUMBER(9),
  ALMOST_DEAD         NUMBER,
  SYNC_SV_ID          NUMBER(9),
  FLAG_PROVENIENZA    VARCHAR2(1 BYTE)
)
COLUMN SHAPE NOT SUBSTITUTABLE AT ALL LEVELS
VARRAY "SHAPE"."SDO_ELEM_INFO" STORE AS LOB (tablespace SITIPIOPR_lob)
VARRAY "SHAPE"."SDO_ORDINATES" STORE AS LOB (tablespace SITIPIOPR_lob)
TABLESPACE SITIPIOPR_TBL;

CREATE TABLE SITISUOLO
(
  COD_NAZIONALE       CHAR(4 BYTE)              NOT NULL,
  FOGLIO              NUMBER(4)                 NOT NULL,
  PARTICELLA          CHAR(5 BYTE)              NOT NULL,
  SUB                 VARCHAR2(3 BYTE)          NOT NULL,
  PROG_POLIGONO       NUMBER(5)                 NOT NULL,
  DATA_FINE_VAL       DATE                      NOT NULL,
  ALLEGATO            CHAR(1 BYTE)              DEFAULT '0'                   NOT NULL,
  SVILUPPO            CHAR(1 BYTE)              DEFAULT '0'                   NOT NULL,
  CAMPAGNA            NUMBER(4)                 DEFAULT 2011,
  UTENTE              VARCHAR2(100 BYTE)        NOT NULL,
  DATA_INIZIO_VAL     DATE,
  DATA_LAV            DATE                      DEFAULT SYSDATE               NOT NULL,
  AREA_COLT           NUMBER(11,2),
  COD_COLTURA         NUMBER(3),
  SHAPE               MDSYS.SDO_GEOMETRY,
  ANNO_FOTO           NUMBER(4),
  MESE_FOTO           NUMBER(2),
  SE_ROW_ID           NUMBER(10)                NOT NULL,
  COD_VARIETA         NUMBER(5),
  TARA                NUMBER(11,2),
  ISTATP              NUMBER(3),
  COD_UTIL            NUMBER(3),
  STATO_COLT          NUMBER(2),
  STATO_PROP          NUMBER(1)                 DEFAULT 0,
  UTENTE_FINE         VARCHAR2(100 BYTE),
  UTENTE_PROP         VARCHAR2(100 BYTE),
  UTENTE_PROP_FINE    VARCHAR2(100 BYTE),
  ID_TRASF            NUMBER(9)                 DEFAULT 0,
  ID_TRASF_FINE       NUMBER(9)                 DEFAULT 0,
  SORGENTE            NUMBER(9),
  VALI_PROD           NUMBER(1),
  TAVOLA              NUMBER(4),
  FLAGCARICO          NUMBER(9),
  DATA_AGGIORNAMENTO  DATE,
  GRUPPO              NUMBER(9),
  ID_PARTICELLA       NUMBER(9),
  IDFOTO              NUMBER(9),
  DXFOTO              NUMBER(3),
  DYFOTO              NUMBER(3),
  ALMOST_DEAD         NUMBER,
  FLAG_PROVENIENZA    VARCHAR2(1 BYTE),
  SYNC_SV_ID          NUMBER(9),
  ID_CONTROLLO        NUMBER(9)
)	
COLUMN SHAPE NOT SUBSTITUTABLE AT ALL LEVELS
VARRAY "SHAPE"."SDO_ELEM_INFO" STORE AS LOB (tablespace SITIPIOPR_lob)
VARRAY "SHAPE"."SDO_ORDINATES" STORE AS LOB (tablespace SITIPIOPR_lob)
TABLESPACE SITIPIOPR_TBL;

CREATE TABLE QGIS_W_SITISUOLO
(
  COD_NAZIONALE       CHAR(4 BYTE)              NOT NULL,
  FOGLIO              NUMBER(4)                 NOT NULL,
  PARTICELLA          CHAR(5 BYTE)              NOT NULL,
  SUB                 VARCHAR2(3 BYTE)          NOT NULL,
  PROG_POLIGONO       NUMBER(5)                 NOT NULL,
  DATA_FINE_VAL       DATE                      NOT NULL,
  ALLEGATO            CHAR(1 BYTE)              DEFAULT '0'                   NOT NULL,
  SVILUPPO            CHAR(1 BYTE)              DEFAULT '0'                   NOT NULL,
  CAMPAGNA            NUMBER(4)                 DEFAULT 2011,
  UTENTE              VARCHAR2(100 BYTE)        NOT NULL,
  DATA_INIZIO_VAL     DATE,
  DATA_LAV            DATE                      DEFAULT SYSDATE               NOT NULL,
  AREA_COLT           NUMBER(11,2),
  COD_COLTURA         NUMBER(3),
  SHAPE               MDSYS.SDO_GEOMETRY,
  ANNO_FOTO           NUMBER(4),
  MESE_FOTO           NUMBER(2),
  SE_ROW_ID           NUMBER(10)                NOT NULL,
  COD_VARIETA         NUMBER(5),
  TARA                NUMBER(11,2),
  ISTATP              NUMBER(3),
  COD_UTIL            NUMBER(3),
  STATO_COLT          NUMBER(2),
  STATO_PROP          NUMBER(1)                 DEFAULT 0,
  UTENTE_FINE         VARCHAR2(100 BYTE),
  UTENTE_PROP         VARCHAR2(100 BYTE),
  UTENTE_PROP_FINE    VARCHAR2(100 BYTE),
  ID_TRASF            NUMBER(9)                 DEFAULT 0,
  ID_TRASF_FINE       NUMBER(9)                 DEFAULT 0,
  SORGENTE            NUMBER(9),
  VALI_PROD           NUMBER(1),
  TAVOLA              NUMBER(4),
  FLAGCARICO          NUMBER(9),
  DATA_AGGIORNAMENTO  DATE,
  GRUPPO              NUMBER(9),
  ID_PARTICELLA       NUMBER(9),
  IDFOTO              NUMBER(9),
  DXFOTO              NUMBER(3),
  DYFOTO              NUMBER(3),
  ALMOST_DEAD         NUMBER,
  FLAG_PROVENIENZA    VARCHAR2(1 BYTE),
  SYNC_SV_ID          NUMBER(9),
  ID_CONTROLLO        NUMBER(9)
)	
COLUMN SHAPE NOT SUBSTITUTABLE AT ALL LEVELS
VARRAY "SHAPE"."SDO_ELEM_INFO" STORE AS LOB (tablespace SITIPIOPR_lob)
VARRAY "SHAPE"."SDO_ORDINATES" STORE AS LOB (tablespace SITIPIOPR_lob)
TABLESPACE SITIPIOPR_TBL;

CREATE INDEX IE1_QGIS_W_SITIPART ON QGIS_W_SITIPART
(COD_NAZIONALE, TAVOLA, PARTICELLA, SUB, DATA_FINE_VAL)
TABLESPACE SITIPIOPR_IDX;

CREATE INDEX IE1_QGIS_W_SITISUOLO ON QGIS_W_SITISUOLO
(COD_NAZIONALE, FOGLIO, PARTICELLA, SUB, DATA_FINE_VAL, 
PROG_POLIGONO)
TABLESPACE SITIPIOPR_IDX;

ALTER TABLE QGIS_T_SUOLO_RILEVATO ADD 
    ( 
     SE_ROW_ID NUMBER (10)  NOT NULL 
    ) 
;

ALTER TABLE QGIS_T_SUOLO_PARTICELLA ADD 
    ( 
     SE_ROW_ID NUMBER (10)  NOT NULL 
    ) 
;

CREATE TABLE CATA_FOGL
(
  ID_FOGLIO         NUMBER(9)                   NOT NULL,
  ID_SEZIONE        NUMBER(9),
  FOGLIO            NUMBER(4)                   NOT NULL,
  INIZIO            DATE                        NOT NULL,
  FINE              DATE                        NOT NULL,
  FLAG_STATO        NUMBER(1),
  DATA_IMPIANTO     DATE,
  TO_SYNC           NUMBER,
  LAST_LPIS_IMPORT  DATE
)
TABLESPACE SITIPIOPR_TBL;

COMMENT ON TABLE CATA_FOGL IS 'fogli del comune';

COMMENT ON COLUMN CATA_FOGL.ID_FOGLIO IS 'id univoco del foglio (FOGL_SEQ)';

COMMENT ON COLUMN CATA_FOGL.ID_SEZIONE IS 'id univoco della sezione di appartenenza';

COMMENT ON COLUMN CATA_FOGL.FOGLIO IS 'numero del foglio';

COMMENT ON COLUMN CATA_FOGL.INIZIO IS 'data inizio validita';

COMMENT ON COLUMN CATA_FOGL.FINE IS 'data fine validita';

COMMENT ON COLUMN CATA_FOGL.FLAG_STATO IS 'STATO DEL FOGLIO: 0 = FOGLIO ORDINARIO; 1 = FOGLIO NON DISPONIBILE;2 = FOGLIO RISERVATO';

COMMENT ON COLUMN CATA_FOGL.DATA_IMPIANTO IS 'DATA DI IMPIANTO, VINCE RISPETTO A QUELLA DELLA SEZIONE';

COMMENT ON COLUMN CATA_FOGL.TO_SYNC IS '1 IN CASO DI SYNC PARZIALE SUL COMUNE';

COMMENT ON COLUMN CATA_FOGL.LAST_LPIS_IMPORT IS 'DATE OF LAST LPIS IMPORT (CXF)';


CREATE UNIQUE INDEX CATA_FOGL_PK ON CATA_FOGL
(ID_FOGLIO)
TABLESPACE SITIPIOPR_IDX;


CREATE UNIQUE INDEX CATA_FOGL_UK ON CATA_FOGL
(ID_SEZIONE, FOGLIO)
TABLESPACE SITIPIOPR_IDX;


CREATE INDEX TMP_CF_FG_IS_IF ON CATA_FOGL
(FOGLIO, ID_SEZIONE, ID_FOGLIO)
TABLESPACE SITIPIOPR_IDX;


CREATE INDEX TMP_CTFG_IS_IF_FG_FST ON CATA_FOGL
(ID_SEZIONE, ID_FOGLIO, FOGLIO, FLAG_STATO)
TABLESPACE SITIPIOPR_IDX;


ALTER TABLE CATA_FOGL ADD (
  CONSTRAINT CATA_FOGL_PK
  PRIMARY KEY
  (ID_FOGLIO)
  USING INDEX CATA_FOGL_PK
  ENABLE VALIDATE);

CREATE TABLE EFA_ELEMENTI
(
  CODICE_EFA            NUMBER                  NOT NULL,
  DESCRIZIONE           VARCHAR2(200 CHAR),
  EP                    VARCHAR2(20 CHAR),
  FATTORE_CONVERSIONE   NUMBER,
  FATTORE_PONDERAZIONE  NUMBER,
  ELAB_VIRT             VARCHAR2(20 CHAR)
)
TABLESPACE SITIPIOPR_TBL
;

COMMENT ON TABLE EFA_ELEMENTI IS 'Aree di interesse ecologico (EFA)';

COMMENT ON COLUMN EFA_ELEMENTI.CODICE_EFA IS 'Codice EFA';

COMMENT ON COLUMN EFA_ELEMENTI.DESCRIZIONE IS 'Descrizione del codice EFA';

COMMENT ON COLUMN EFA_ELEMENTI.EP IS '"EP" se Elemento del Paesaggio, altrimenti "NO-EP"';

COMMENT ON COLUMN EFA_ELEMENTI.FATTORE_CONVERSIONE IS 'Fattore di conversione';

COMMENT ON COLUMN EFA_ELEMENTI.FATTORE_PONDERAZIONE IS 'Fattore di ponderazione';

COMMENT ON COLUMN EFA_ELEMENTI.ELAB_VIRT IS 'Valori: V (l''elaborazione virtuale va eseguita), R (va eseguita l''elaborazione reale annche quando viene chiamata quella virtuale';



CREATE TABLE EFA_QUADRO_LAYER
(
  ID_RF_QUADRO_EFA   NUMBER                     NOT NULL,
  SHAPE              MDSYS.SDO_GEOMETRY,
  TIPO               VARCHAR2(15 BYTE),
  DATA_INIZIO        DATE,
  DATA_FINE          DATE,
  GRID_ID            NUMBER,
  ID_GEOM            NUMBER,
  LENGTH_LINEA       NUMBER,
  ID_POLI_RIF        NUMBER,
  COD_VARIETA        NUMBER,
  NUM_ELENCO         NUMBER,
  AREA               NUMBER(10),
  COD_VARIETA_EFA    NUMBER,
  UTENTE_LAV         VARCHAR2(100 BYTE),
  COD_VARIETA_MERGE  NUMBER,
  SUP                NUMBER,
  TAB_ORIGIN         VARCHAR2(2 BYTE)
)
COLUMN SHAPE NOT SUBSTITUTABLE AT ALL LEVELS
VARRAY "SHAPE"."SDO_ELEM_INFO" STORE AS LOB (tablespace SITIPIOPR_lob)
VARRAY "SHAPE"."SDO_ORDINATES" STORE AS LOB (tablespace SITIPIOPR_lob)
TABLESPACE SITIPIOPR_TBL
;

COMMENT ON COLUMN EFA_QUADRO_LAYER.ID_RF_QUADRO_EFA IS 'identificativo del record della EGEOSDBAE.RF_QUADRO_EFA_BB/EGEOSDBAE.RF_QUADRO_EFA_CO (chiave della tabella con il campo TAB_ORIGIN)';

COMMENT ON COLUMN EFA_QUADRO_LAYER.SHAPE IS 'geometria ';

COMMENT ON COLUMN EFA_QUADRO_LAYER.DATA_INIZIO IS 'data di inizio validita';

COMMENT ON COLUMN EFA_QUADRO_LAYER.DATA_FINE IS 'data di fine validita';

COMMENT ON COLUMN EFA_QUADRO_LAYER.GRID_ID IS 'identificativo della griglia';

COMMENT ON COLUMN EFA_QUADRO_LAYER.COD_VARIETA IS 'codice varieta ';

COMMENT ON COLUMN EFA_QUADRO_LAYER.NUM_ELENCO IS 'ortofoto di riferimento (dettagli nella tabella contesti_applicativi)';

COMMENT ON COLUMN EFA_QUADRO_LAYER.COD_VARIETA_EFA IS 'codice varieta EFA attribuito al poligono (se valorizzato ricopre il campo COD_VARIETA)';

COMMENT ON COLUMN EFA_QUADRO_LAYER.UTENTE_LAV IS 'utente di lavorazione';

COMMENT ON COLUMN EFA_QUADRO_LAYER.COD_VARIETA_MERGE IS 'codice varieta dell''elemento Refresh (COD_VARIETA_EFA se valorizzato, altrimenti COD_VARIETA)';

COMMENT ON COLUMN EFA_QUADRO_LAYER.SUP IS 'superficie poligono ';

COMMENT ON COLUMN EFA_QUADRO_LAYER.TAB_ORIGIN IS 'tabella di origine del dato: BB se  EGEOSDBAE.RF_QUADRO_EFA_BB, CO se  EGEOSDBAE.RF_QUADRO_EFA_CO';



CREATE TABLE ELENCHI_HEADER
(
  ID_ELENCO               VARCHAR2(20 BYTE)     NOT NULL,
  DESCRIZIONE             VARCHAR2(255 BYTE)    NOT NULL,
  TIPO_ELENCO             VARCHAR2(1 BYTE)      NOT NULL,
  DATA_INSE               DATE                  DEFAULT SYSDATE,
  DATA_CHIUSURA_ATTIVITA  DATE,
  NUM_ELENCO              NUMBER(9)             NOT NULL,
  TIPO_LAVO               NUMBER(2),
  CAMPAGNA                NUMBER(4)             DEFAULT 2011                  NOT NULL,
  AUTO_SAL                NUMBER(1),
  IS_WORK                 NUMBER,
  ECZ_REQ                 VARCHAR2(255 BYTE),
  SOURCE_REQ              VARCHAR2(255 BYTE),
  MULTIPLE_TIMES          NUMBER,
  WORK_LIFE               NUMBER,
  FL_NOTES_GR_PROP        NUMBER,
  FL_NOTES                NUMBER,
  DOC_REQ_MODE            NUMBER,
  CHECK_AOI               NUMBER,
  CONTEXT_VISIBILITY      VARCHAR2(100 BYTE),
  DATA_IMMI_ELEN          DATE
)
TABLESPACE SITIPIOPR_TBL
;

COMMENT ON TABLE ELENCHI_HEADER IS 'ElenchiLavorazione - Header';

COMMENT ON COLUMN ELENCHI_HEADER.ID_ELENCO IS 'ID ELENCO';

COMMENT ON COLUMN ELENCHI_HEADER.DESCRIZIONE IS 'DESCRIZIONE ELENCO';

COMMENT ON COLUMN ELENCHI_HEADER.TIPO_ELENCO IS 'TIPO ELENCO (P=PARTICELLE - F=FOGLI)';

COMMENT ON COLUMN ELENCHI_HEADER.DATA_INSE IS 'DATA INSERIMENTO';

COMMENT ON COLUMN ELENCHI_HEADER.DATA_CHIUSURA_ATTIVITA IS 'DATA CHIUSURA ATTIVITA';

COMMENT ON COLUMN ELENCHI_HEADER.NUM_ELENCO IS 'FK SU ELENCHI_HEADER.NUM_ELENCO';

COMMENT ON COLUMN ELENCHI_HEADER.TIPO_LAVO IS 'SEE SITILISTALAV.TIPOLAVORAZIONE';

COMMENT ON COLUMN ELENCHI_HEADER.CAMPAGNA IS 'CAMPAGNA DI LAVORAZIONE';

COMMENT ON COLUMN ELENCHI_HEADER.AUTO_SAL IS 'SAL CALCOLATO IN AUTOMATICO';

COMMENT ON COLUMN ELENCHI_HEADER.IS_WORK IS 'ELENCO UTILIZZABILE IN PROCESSO ISTANZA DI RIESAME';

COMMENT ON COLUMN ELENCHI_HEADER.ECZ_REQ IS 'LIST OF ECZ FOR OPEN A JOB REQUEST';

COMMENT ON COLUMN ELENCHI_HEADER.SOURCE_REQ IS 'SOURCE OF LAND USE FOR OPEN A JOB REQUEST';

COMMENT ON COLUMN ELENCHI_HEADER.MULTIPLE_TIMES IS 'IF = 0 CANNOT INSERT NEW JOB REQUEST IF ALREADY WORKED';

COMMENT ON COLUMN ELENCHI_HEADER.WORK_LIFE IS 'CHECK IF MAX(SITISUOLO.DATA_INIZIO_VAL,SITICOND.DATA_INIZIO) + WORK_LIFE > SYSDATE';

COMMENT ON COLUMN ELENCHI_HEADER.FL_NOTES_GR_PROP IS '1 = NOTES MANDATORY ON GRAPH PROPOSAL';

COMMENT ON COLUMN ELENCHI_HEADER.FL_NOTES IS '1 = NOTES MANDATORY ON ALPHANUMERIC SEGNALATION';

COMMENT ON COLUMN ELENCHI_HEADER.DOC_REQ_MODE IS 'NULL,0 NO CONTROL; 1 CHECK PRESENCE OF ALL ELENCHI_DOC DOCUMENTS; 2 CHECK IF AT LEAST ONE ELENCHI_DOC';

COMMENT ON COLUMN ELENCHI_HEADER.CHECK_AOI IS 'NULL,0 NO CONTROL; 1 CHECK IF PARCEL IS ON AREAOFINTEREST; 2 CHECK IF PARCEL IS OUT OF AREAOFINTEREST';

COMMENT ON COLUMN ELENCHI_HEADER.CONTEXT_VISIBILITY IS 'BO=BACKOFFICE, LPIS E ALL=SIA BO CHE LPIS';

COMMENT ON COLUMN ELENCHI_HEADER.DATA_IMMI_ELEN IS 'Joblist''s reference date';



CREATE TABLE GIS_REGI
(
  ID_REGI  NUMBER(9)                            NOT NULL,
  FUSO     VARCHAR2(1 BYTE),
  SHAPE    MDSYS.SDO_GEOMETRY
)
COLUMN SHAPE NOT SUBSTITUTABLE AT ALL LEVELS
VARRAY "SHAPE"."SDO_ELEM_INFO" STORE AS LOB (tablespace SITIPIOPR_lob)
VARRAY "SHAPE"."SDO_ORDINATES" STORE AS LOB (tablespace SITIPIOPR_lob)
TABLESPACE SITIPIOPR_TBL
;

COMMENT ON TABLE GIS_REGI IS 'GIS - limiti regione';

COMMENT ON COLUMN GIS_REGI.ID_REGI IS 'ID regione';

COMMENT ON COLUMN GIS_REGI.FUSO IS 'Fuso di riferimento (W=Fuso Ovest, E=Fuso Est)';

COMMENT ON COLUMN GIS_REGI.SHAPE IS 'Geometria';



CREATE TABLE GIS_TAVO
(
  ID_FOGLIO           NUMBER(9),
  ID_TAVO             NUMBER(9)                 NOT NULL,
  TAVOLA              NUMBER(4)                 NOT NULL,
  INIZIO              DATE                      NOT NULL,
  FINE                DATE                      NOT NULL,
  SHAPE               MDSYS.SDO_GEOMETRY,
  DATA_AGGIORNAMENTO  DATE
)
COLUMN SHAPE NOT SUBSTITUTABLE AT ALL LEVELS
VARRAY "SHAPE"."SDO_ELEM_INFO" STORE AS LOB (tablespace SITIPIOPR_lob)
VARRAY "SHAPE"."SDO_ORDINATES" STORE AS LOB (tablespace SITIPIOPR_lob)
TABLESPACE SITIPIOPR_TBL
;

COMMENT ON TABLE GIS_TAVO IS 'tavole di un foglio';

COMMENT ON COLUMN GIS_TAVO.ID_FOGLIO IS 'id univoco del foglio di appartenenza';

COMMENT ON COLUMN GIS_TAVO.ID_TAVO IS 'id univoco della tavola (FOGL_SEQ)';

COMMENT ON COLUMN GIS_TAVO.TAVOLA IS 'numero tavola';

COMMENT ON COLUMN GIS_TAVO.INIZIO IS 'data inizio validita';

COMMENT ON COLUMN GIS_TAVO.FINE IS 'data fine validita';

COMMENT ON COLUMN GIS_TAVO.SHAPE IS 'geometrie della tavola';



CREATE TABLE RF_QUADRO
(
  GRID_ID       NUMBER(9)                       NOT NULL,
  FL_STATO      NUMBER(9),
  DATA_ANALISI  DATE,
  DATA_LAV      DATE,
  DATA_PART     DATE,
  UTENTE_LAV    VARCHAR2(100 BYTE),
  UTENTE_SOSP   VARCHAR2(100 BYTE),
  DATA_SOSP     DATE,
  NOTE_SOSP     VARCHAR2(1024 BYTE),
  NUM_ELENCO    NUMBER(9)                       NOT NULL,
  COD_AGRO      NUMBER(9)                       DEFAULT 0                     NOT NULL,
  ID_PROV       NUMBER
)
TABLESPACE SITIPIOPR_TBL
;

COMMENT ON TABLE RF_QUADRO IS 'REFRESH QUADRI IN LAVORAZIONE';

COMMENT ON COLUMN RF_QUADRO.GRID_ID IS 'ID GRIGLIA';

COMMENT ON COLUMN RF_QUADRO.FL_STATO IS '0 = NON FATTO; 1 = COMPLETO; 2 = SOSPESO';

COMMENT ON COLUMN RF_QUADRO.UTENTE_SOSP IS 'Utente sospensione';

COMMENT ON COLUMN RF_QUADRO.DATA_SOSP IS 'Data sospensione';

COMMENT ON COLUMN RF_QUADRO.NOTE_SOSP IS 'Note sospensione';

COMMENT ON COLUMN RF_QUADRO.COD_AGRO IS 'Usa codifica agricola? 0=usa estesa 1=usa agricola';



CREATE TABLE RF_QUADRO_ALT
(
  GRID_ID     NUMBER(9)                         NOT NULL,
  NUM_ELENCO  NUMBER(9)                         NOT NULL,
  ELENCO_RIF  NUMBER(9)                         NOT NULL,
  COD_AGRO    NUMBER(9)                         NOT NULL
)
TABLESPACE SITIPIOPR_TBL
;

COMMENT ON TABLE RF_QUADRO_ALT IS 'REFRESH quadri con strato di riferimento alternativo rispetto a quello indicato per la provincia';

COMMENT ON COLUMN RF_QUADRO_ALT.GRID_ID IS 'ID griglia';

COMMENT ON COLUMN RF_QUADRO_ALT.NUM_ELENCO IS 'Numero elenco';

COMMENT ON COLUMN RF_QUADRO_ALT.ELENCO_RIF IS 'Numero elenco di riferimento';

COMMENT ON COLUMN RF_QUADRO_ALT.COD_AGRO IS 'Usa codifica agricola? 0=usa estesa 1=usa agricola';



CREATE TABLE RF_QUADRO_DIFF
(
  PKID         NUMBER(9)                        NOT NULL,
  GRID_ID      NUMBER(9)                        NOT NULL,
  PROG_SUOLO   NUMBER(9)                        NOT NULL,
  SHAPE        MDSYS.SDO_GEOMETRY,
  COD_VARIETA  NUMBER(9)                        NOT NULL,
  NUM_ELENCO   NUMBER(9)                        NOT NULL,
  FLAG_VARI    NUMBER(9)                        DEFAULT 0                     NOT NULL
)
COLUMN SHAPE NOT SUBSTITUTABLE AT ALL LEVELS
VARRAY "SHAPE"."SDO_ELEM_INFO" STORE AS LOB (tablespace SITIPIOPR_lob)
VARRAY "SHAPE"."SDO_ORDINATES" STORE AS LOB (tablespace SITIPIOPR_lob)
TABLESPACE SITIPIOPR_TBL
;

COMMENT ON TABLE RF_QUADRO_DIFF IS 'REFRESH QUADRI ECLATANZE';

COMMENT ON COLUMN RF_QUADRO_DIFF.GRID_ID IS 'ID GRIGLIA';

COMMENT ON COLUMN RF_QUADRO_DIFF.PROG_SUOLO IS 'PROGRESSIVO SUOLO REFRESH';

COMMENT ON COLUMN RF_QUADRO_DIFF.COD_VARIETA IS 'CODICE DI USO SUOLO';

COMMENT ON COLUMN RF_QUADRO_DIFF.NUM_ELENCO IS 'LEGAME CON L`ELENCO DI LAVORAZIONE';

COMMENT ON COLUMN RF_QUADRO_DIFF.FLAG_VARI IS '1=VARIAZIONE SUL MACROCODICE AGRICOLO (RA)';



CREATE TABLE RF_QUADRO_SUOLO
(
  PKID         NUMBER(9)                        NOT NULL,
  GRID_ID      NUMBER(9)                        NOT NULL,
  PROG_SUOLO   NUMBER(9)                        NOT NULL,
  SHAPE        MDSYS.SDO_GEOMETRY,
  COD_VARIETA  NUMBER(9)                        NOT NULL,
  NUM_ELENCO   NUMBER(9)                        NOT NULL
)
COLUMN SHAPE NOT SUBSTITUTABLE AT ALL LEVELS
VARRAY "SHAPE"."SDO_ELEM_INFO" STORE AS LOB (tablespace SITIPIOPR_lob)
VARRAY "SHAPE"."SDO_ORDINATES" STORE AS LOB (tablespace SITIPIOPR_lob)
TABLESPACE SITIPIOPR_TBL
;

COMMENT ON TABLE RF_QUADRO_SUOLO IS 'REFRESH QUADRI SUOLO';

COMMENT ON COLUMN RF_QUADRO_SUOLO.GRID_ID IS 'ID GRIGLIA';

COMMENT ON COLUMN RF_QUADRO_SUOLO.PROG_SUOLO IS 'PROGRESSIVO POLIGONO';

COMMENT ON COLUMN RF_QUADRO_SUOLO.COD_VARIETA IS 'CODICE DI USO SUOLO';



CREATE TABLE SITICODS_VARI
(
  COD_VARI            NUMBER(3)                 NOT NULL,
  DESCRIZIONE         VARCHAR2(255 BYTE)        NOT NULL,
  DESC_BREVE          VARCHAR2(10 BYTE),
  TIPO_UNAR           NUMBER(1),
  DATA_AGGIORNAMENTO  DATE                      DEFAULT sysdate,
  FL_SAU              NUMBER(1)                 DEFAULT 1,
  DESCRIZIONE_INT     VARCHAR2(250 CHAR)
)
TABLESPACE SITIPIOPR_TBL
;

COMMENT ON TABLE SITICODS_VARI IS 'Codici utilizzo suolo - descrizioni varietà';

COMMENT ON COLUMN SITICODS_VARI.COD_VARI IS 'Codice varietà';

COMMENT ON COLUMN SITICODS_VARI.DESCRIZIONE IS 'Descrizione varietà';

COMMENT ON COLUMN SITICODS_VARI.DESC_BREVE IS 'Descrizione breve (sigla) della varietà';

COMMENT ON COLUMN SITICODS_VARI.TIPO_UNAR IS 'Tipo unità arborea (sitiunar_deco)';

COMMENT ON COLUMN SITICODS_VARI.DATA_AGGIORNAMENTO IS 'Data di aggiornamento del record';



CREATE TABLE SITILISTALAV
(
  ID_LAV              NUMBER(9)                 NOT NULL,
  COD_SETTORE         NUMBER(9)                 NOT NULL,
  PROV_RIF            VARCHAR2(20 CHAR)         NOT NULL,
  CAMPAGNA            NUMBER(4)                 NOT NULL,
  DATA_IMMI_ELEN      DATE,
  DESCRIZIONE         VARCHAR2(30 BYTE)         NOT NULL,
  TIPOLAVORAZIONE     NUMBER(2)                 NOT NULL,
  PROV_RIF_ALT        VARCHAR2(9 BYTE),
  ID_LAV_ALT          VARCHAR2(9 BYTE),
  CTRLOGG             NUMBER(9),
  AUTO_SAL            NUMBER(1),
  DATA_AGGIORNAMENTO  DATE,
  CONTEXT_VISIBILITY  VARCHAR2(100 BYTE),
  COMP_CHECK_TYPE     NUMBER                    DEFAULT 0                     NOT NULL
)
TABLESPACE SITIPIOPR_TBL
;

COMMENT ON COLUMN SITILISTALAV.ID_LAV IS 'Primary Key';

COMMENT ON COLUMN SITILISTALAV.COD_SETTORE IS 'Sector Code';

COMMENT ON COLUMN SITILISTALAV.PROV_RIF IS 'Reference Province for the Ordinary Joblist';

COMMENT ON COLUMN SITILISTALAV.CAMPAGNA IS 'Year of Campaign';

COMMENT ON COLUMN SITILISTALAV.DATA_IMMI_ELEN IS 'Joblist''s reference date';

COMMENT ON COLUMN SITILISTALAV.DESCRIZIONE IS 'Description';

COMMENT ON COLUMN SITILISTALAV.TIPOLAVORAZIONE IS 'TIPO DI LAVORAZIONE: 1 = IN CAMPO 2 = FOTOINTERPRETAZIONE 3 = LAVORAZIONE CATASTALE 4 = SATELLITE 5 = URBANO 10 = PROPOSTA';

COMMENT ON COLUMN SITILISTALAV.CTRLOGG IS 'Flag Controlli oggettivi';

COMMENT ON COLUMN SITILISTALAV.AUTO_SAL IS '1=auto-inserting into the JPS (SAL)';

COMMENT ON COLUMN SITILISTALAV.DATA_AGGIORNAMENTO IS 'Last update date';

COMMENT ON COLUMN SITILISTALAV.CONTEXT_VISIBILITY IS 'Joblist''s visualization context: ''LPIS''=viewer WEB; ''BO''=Client BO; ''ALL''=Anywhere';



CREATE TABLE SITILOAD_INDIRIZZI
(
  ID_INDIRIZZO     NUMBER(9)                    NOT NULL,
  INDIRIZZO        VARCHAR2(255 BYTE)           NOT NULL,
  USERNAME         VARCHAR2(255 BYTE)           NOT NULL,
  PASSWORD         VARCHAR2(255 BYTE)           NOT NULL,
  DESCRIZIONE      VARCHAR2(255 BYTE)           NOT NULL,
  FORMATO          NUMBER(2)                    DEFAULT 0                     NOT NULL,
  AGGIORNA_SOGG    NUMBER(1)                    DEFAULT 0,
  DATA_SOGGETTI    DATE,
  VALIDANTE        NUMBER(1)                    DEFAULT 0                     NOT NULL,
  COD_SOFTWARE     VARCHAR2(100 BYTE),
  COD_MODULO       VARCHAR2(100 BYTE),
  SUOLO_CERT       NUMBER(1),
  CONNECTION_SYNC  VARCHAR2(255 CHAR),
  WHAT_SYNC        VARCHAR2(255 CHAR)
)
TABLESPACE SITIPIOPR_TBL
;

COMMENT ON TABLE SITILOAD_INDIRIZZI IS 'Caricamento - URL delle fonti di aggiornamento';

COMMENT ON COLUMN SITILOAD_INDIRIZZI.CONNECTION_SYNC IS 'DBGIS CONNECTION SOURCE OF SYNC';

COMMENT ON COLUMN SITILOAD_INDIRIZZI.WHAT_SYNC IS 'WHAT TO SYNC';



CREATE TABLE SITIPART
(
  COD_NAZIONALE       CHAR(4 BYTE)              NOT NULL,
  FOGLIO              NUMBER(4)                 NOT NULL,
  PARTICELLA          CHAR(5 BYTE)              NOT NULL,
  SUB                 VARCHAR2(3 BYTE)          NOT NULL,
  DATA_LAV            DATE                      DEFAULT SYSDATE               NOT NULL,
  ALLEGATO            CHAR(1 BYTE)              DEFAULT '0'                   NOT NULL,
  SVILUPPO            CHAR(1 BYTE)              DEFAULT '0'                   NOT NULL,
  UTENTE              VARCHAR2(100 BYTE)        NOT NULL,
  DATA_INIZIO_VAL     DATE                      NOT NULL,
  DATA_FINE_VAL       DATE                      NOT NULL,
  SHAPE               MDSYS.SDO_GEOMETRY,
  AREA_PART           NUMBER(11,2),
  DELTA_X_FOTO        NUMBER(5,2),
  DELTA_Y_FOTO        NUMBER(5,2),
  CONTRASTO           NUMBER(3),
  LUMINOSITA          NUMBER(3),
  COD_DIGI            NUMBER(2),
  COD_EDIF            NUMBER(2),
  FLAG1               CHAR(3 BYTE),
  FLAG2               CHAR(3 BYTE),
  FLAG3               CHAR(3 BYTE),
  SE_ROW_ID           NUMBER(10)                NOT NULL,
  NOTE                VARCHAR2(255 BYTE),
  ISTATP              NUMBER(3),
  STATO_PROP          NUMBER(1)                 DEFAULT 0,
  UTENTE_FINE         VARCHAR2(100 BYTE),
  UTENTE_PROP         VARCHAR2(100 BYTE),
  UTENTE_PROP_FINE    VARCHAR2(100 BYTE),
  ID_TRASF            NUMBER(9)                 DEFAULT 0,
  ID_TRASF_FINE       NUMBER(9)                 DEFAULT 0,
  SORGENTE            NUMBER(9),
  VALI_PROD           NUMBER(1),
  TAVOLA              NUMBER(4),
  FLAGCARICO          NUMBER(9),
  DATA_AGGIORNAMENTO  DATE,
  ID_PARTICELLA       NUMBER(9),
  ID_CATA_PART        NUMBER(9),
  ALMOST_DEAD         NUMBER,
  FLAG_PROVENIENZA    VARCHAR2(1 BYTE),
  SYNC_SV_ID          NUMBER(9)
)
COLUMN SHAPE NOT SUBSTITUTABLE AT ALL LEVELS
VARRAY "SHAPE"."SDO_ELEM_INFO" STORE AS LOB (tablespace SITIPIOPR_lob)
VARRAY "SHAPE"."SDO_ORDINATES" STORE AS LOB (tablespace SITIPIOPR_lob)
TABLESPACE SITIPIOPR_TBL
;


CREATE TABLE SITI_PART_DA_ELAB
(
  COD_NAZIONALE         CHAR(4 BYTE)            NOT NULL,
  FOGLIO                NUMBER(4)               NOT NULL,
  PARTICELLA            CHAR(5 BYTE)            NOT NULL,
  SUB                   VARCHAR2(3 BYTE)        NOT NULL,
  DATA_RICHIESTA        DATE                    DEFAULT SYSDATE               NOT NULL,
  DATA_ELABORAZIONE_OP  DATE
)
TABLESPACE SITIPIOPR_TBL
;

COMMENT ON COLUMN SITI_PART_DA_ELAB.DATA_RICHIESTA IS 'data richiesta sincronizzazione particella';

COMMENT ON COLUMN SITI_PART_DA_ELAB.DATA_ELABORAZIONE_OP IS 'data elaborazione particella da parte dell¿OP';



CREATE TABLE SITIPLAV
(
  COD_NAZIONALE       VARCHAR2(4 BYTE)          NOT NULL,
  FOGLIO              NUMBER(4)                 NOT NULL,
  PARTICELLA          VARCHAR2(5 BYTE)          NOT NULL,
  SUB                 VARCHAR2(3 BYTE)          NOT NULL,
  DATA_LAV_P_GIS      DATE,
  DATA_LAV_T_GIS      DATE,
  COD_LAVORAZIONE     VARCHAR2(1 BYTE),
  UTENTE              VARCHAR2(100 BYTE),
  DATA_LAV            DATE,
  COD_AGRO            VARCHAR2(11 BYTE),
  DATA_CAMPO          DATE,
  ISTATP              NUMBER(3),
  ID_LAV              NUMBER(9)                 NOT NULL,
  PROG_LAV            NUMBER(3)                 NOT NULL,
  LAST                NUMBER(1)                 DEFAULT 1                     NOT NULL,
  MOTI_RICH           NUMBER(2)                 DEFAULT 0                     NOT NULL,
  NOTE                VARCHAR2(300 BYTE),
  UNIMM               NUMBER(5),
  STATO_PROP          NUMBER(1)                 DEFAULT 0,
  UTENTEINS           VARCHAR2(100 BYTE)        DEFAULT 'AUTOMATICO',
  DATAINS             DATE                      DEFAULT SYSDATE,
  FLAG_MOTI           VARCHAR2(2 BYTE)          DEFAULT '0',
  DESC_MOTI           VARCHAR2(255 BYTE),
  DATASOSP            DATE,
  UTENTESOSP          VARCHAR2(100 BYTE),
  FLAGSTATO           NUMBER(1),
  ID_PARTICELLA       NUMBER(9),
  DATA_LAV_U_GIS      DATE,
  NOTE_LAV            VARCHAR2(1024 BYTE),
  DATA_AGGIORNAMENTO  DATE,
  SYNC_SV_ID          NUMBER,
  FLAG_MODI_T_GIS     NUMBER(1),
  FLAG_MODI_P_GIS     NUMBER(1),
  SUPE_CATA           NUMBER(8),
  FLAG_STATO_CATA     VARCHAR2(1 BYTE),
  FOGLIOAU            NUMBER(4)
)
TABLESPACE SITIPIOPR_TBL
;

COMMENT ON COLUMN SITIPLAV.FLAG_MODI_T_GIS IS '1=USO DEL SUOLO MODIFICATO RISPETTO ALLA VERSIONE PRECEDENTE, 0=NON MODIFICATO, NULL=NON CALCOLATO';

COMMENT ON COLUMN SITIPLAV.FLAG_MODI_P_GIS IS '1=PARTICELLA MODIFICATA RISPETTO ALLA VERSIONE PRECEDENTE, 0=NON MODIFICATA, NULL=NON CALCOLATO';

COMMENT ON COLUMN SITIPLAV.SUPE_CATA IS 'Cadastral area';

COMMENT ON COLUMN SITIPLAV.FLAG_STATO_CATA IS 'Cadaster status';

COMMENT ON COLUMN SITIPLAV.FOGLIOAU IS '1=austro-hungarian cadaster''s model, 0=otherwise ';




CREATE TABLE CODEX_FONTI_CODICI
(
  ID_FONTE        NUMBER(9)                     NOT NULL,
  COD_VARI        NUMBER(9)                     NOT NULL,
  COD_VARI_FONTE  VARCHAR2(50 BYTE)             NOT NULL
)
TABLESPACE SITIPIOPR_TBL
;

COMMENT ON TABLE CODEX_FONTI_CODICI IS 'Decodifiche - Fonti-codici uso suolo (codici varieta)';

COMMENT ON COLUMN CODEX_FONTI_CODICI.ID_FONTE IS 'Id della fonte';

COMMENT ON COLUMN CODEX_FONTI_CODICI.COD_VARI IS 'Codice varieta'' siti';

COMMENT ON COLUMN CODEX_FONTI_CODICI.COD_VARI_FONTE IS 'Codice varieta'' da fonte';



CREATE TABLE GIS_MAPPE
(
  ID_MAPPA     NUMBER(9)                        NOT NULL,
  ID_TAVO      NUMBER(9),
  ALLEGATO     VARCHAR2(1 BYTE)                 NOT NULL,
  SVILUPPO     VARCHAR2(1 BYTE)                 NOT NULL,
  NOME_MAPPA   VARCHAR2(255 BYTE),
  MAP_TYPE     NUMBER(1)                        NOT NULL,
  MAP_VERSION  VARCHAR2(255 BYTE),
  SCALA        NUMBER(9),
  SHAPE        MDSYS.SDO_GEOMETRY
)
COLUMN SHAPE NOT SUBSTITUTABLE AT ALL LEVELS
VARRAY "SHAPE"."SDO_ELEM_INFO" STORE AS LOB (tablespace SITIPIOPR_lob)
VARRAY "SHAPE"."SDO_ORDINATES" STORE AS LOB (tablespace SITIPIOPR_lob)
TABLESPACE SITIPIOPR_TBL
;

COMMENT ON TABLE GIS_MAPPE IS 'MAPPE RELATIVE AD UNA TAVOLA';

COMMENT ON COLUMN GIS_MAPPE.ID_MAPPA IS 'ID UNIVOCO DELLA MAPPA';

COMMENT ON COLUMN GIS_MAPPE.ID_TAVO IS 'ID UNIVOCO DELLA TAVOLA DI APPARTENENZA';

COMMENT ON COLUMN GIS_MAPPE.NOME_MAPPA IS 'NOME DELLA MAPPA';

COMMENT ON COLUMN GIS_MAPPE.MAP_TYPE IS 'TIPO DELLA MAPPA (1=TIFF SITI;2=DWG SITI)';

COMMENT ON COLUMN GIS_MAPPE.MAP_VERSION IS 'VERSIONE DELLA MAPPA';

COMMENT ON COLUMN GIS_MAPPE.SCALA IS 'SCALA DELLA MAPPA';

alter table SITISUOLO_ATTIVE modify ISTAT_COMUNE null;

drop table SITISUOLO_ATTIVE;

CREATE TABLE SITISUOLO_ATTIVE
(
  COD_NAZIONALE       CHAR(4 BYTE)              NOT NULL,
  FOGLIO              NUMBER(4)                 NOT NULL,
  PARTICELLA          CHAR(5 BYTE)              NOT NULL,
  SUB                 VARCHAR2(3 BYTE)          NOT NULL,
  PROG_POLIGONO       NUMBER(5)                 NOT NULL,
  DATA_FINE_VAL       DATE                      NOT NULL,
  ALLEGATO            CHAR(1 BYTE)              DEFAULT '0'                   NOT NULL,
  SVILUPPO            CHAR(1 BYTE)              DEFAULT '0'                   NOT NULL,
  CAMPAGNA            NUMBER(4)                 DEFAULT 2011,
  UTENTE              VARCHAR2(100 BYTE)        NOT NULL,
  DATA_INIZIO_VAL     DATE,
  DATA_LAV            DATE                      DEFAULT SYSDATE               NOT NULL,
  AREA_COLT           NUMBER(11,2),
  COD_COLTURA         NUMBER(3),
  SHAPE               MDSYS.SDO_GEOMETRY,
  ANNO_FOTO           NUMBER(4),
  MESE_FOTO           NUMBER(2),
  SE_ROW_ID           NUMBER(10)                NOT NULL,
  COD_VARIETA         NUMBER(5),
  TARA                NUMBER(11,2),
  ISTATP              NUMBER(3),
  COD_UTIL            NUMBER(3),
  STATO_COLT          NUMBER(2),
  STATO_PROP          NUMBER(1)                 DEFAULT 0,
  UTENTE_FINE         VARCHAR2(100 BYTE),
  UTENTE_PROP         VARCHAR2(100 BYTE),
  UTENTE_PROP_FINE    VARCHAR2(100 BYTE),
  ID_TRASF            NUMBER(9)                 DEFAULT 0,
  ID_TRASF_FINE       NUMBER(9)                 DEFAULT 0,
  SORGENTE            NUMBER(9),
  VALI_PROD           NUMBER(1),
  TAVOLA              NUMBER(4),
  FLAGCARICO          NUMBER(9),
  DATA_AGGIORNAMENTO  DATE,
  GRUPPO              NUMBER(9),
  ID_PARTICELLA       NUMBER(9),
  IDFOTO              NUMBER(9),
  DXFOTO              NUMBER(3),
  DYFOTO              NUMBER(3),
  ALMOST_DEAD         NUMBER,
  FLAG_PROVENIENZA    VARCHAR2(1 BYTE),
  SYNC_SV_ID          NUMBER(9),
  ID_CONTROLLO        NUMBER(9)
)	
COLUMN SHAPE NOT SUBSTITUTABLE AT ALL LEVELS
VARRAY "SHAPE"."SDO_ELEM_INFO" STORE AS LOB (tablespace SITIPIOPR_lob)
VARRAY "SHAPE"."SDO_ORDINATES" STORE AS LOB (tablespace SITIPIOPR_lob)
TABLESPACE SITIPIOPR_TBL;

CREATE INDEX IE_SITISUOLO_ATTIVE_01 ON SITISUOLO_ATTIVE (COD_NAZIONALE, FOGLIO, PARTICELLA, CAMPAGNA, DATA_INIZIO_VAL) TABLESPACE SITIPIOPR_IDX;

ALTER TABLE QGIS_T_VERSIONE_PARTICELLA ADD 
    ( 
     ID_TIPO_SORGENTE_SUOLO NUMBER (4) 
    ) 
;



ALTER TABLE QGIS_T_VERSIONE_PARTICELLA 
    ADD CONSTRAINT FK_QGIS_D_TIPO_SORGENTE_SUO_03 FOREIGN KEY 
    ( 
     ID_TIPO_SORGENTE_SUOLO
    ) 
    REFERENCES QGIS_D_TIPO_SORGENTE_SUOLO 
    ( 
     ID_TIPO_SORGENTE_SUOLO
    );
	
CREATE TABLE QGIS_W_SITIPLAV
(
  COD_NAZIONALE       VARCHAR2(4 BYTE)          NOT NULL,
  FOGLIO              NUMBER(4)                 NOT NULL,
  PARTICELLA          VARCHAR2(5 BYTE)          NOT NULL,
  SUB                 VARCHAR2(3 BYTE)          NOT NULL,
  DATA_LAV_P_GIS      DATE,
  DATA_LAV_T_GIS      DATE,
  COD_LAVORAZIONE     VARCHAR2(1 BYTE),
  UTENTE              VARCHAR2(100 BYTE),
  DATA_LAV            DATE,
  COD_AGRO            VARCHAR2(11 BYTE),
  DATA_CAMPO          DATE,
  ISTATP              NUMBER(3),
  ID_LAV              NUMBER(9)                 NOT NULL,
  PROG_LAV            NUMBER(3)                 NOT NULL,
  LAST                NUMBER(1)                 DEFAULT 1                     NOT NULL,
  MOTI_RICH           NUMBER(2)                 DEFAULT 0                     NOT NULL,
  NOTE                VARCHAR2(300 BYTE),
  UNIMM               NUMBER(5),
  STATO_PROP          NUMBER(1)                 DEFAULT 0,
  UTENTEINS           VARCHAR2(100 BYTE)        DEFAULT 'AUTOMATICO',
  DATAINS             DATE                      DEFAULT SYSDATE,
  FLAG_MOTI           VARCHAR2(2 BYTE)          DEFAULT '0',
  DESC_MOTI           VARCHAR2(255 BYTE),
  DATASOSP            DATE,
  UTENTESOSP          VARCHAR2(100 BYTE),
  FLAGSTATO           NUMBER(1),
  ID_PARTICELLA       NUMBER(9),
  DATA_LAV_U_GIS      DATE,
  NOTE_LAV            VARCHAR2(1024 BYTE),
  DATA_AGGIORNAMENTO  DATE,
  SYNC_SV_ID          NUMBER,
  FLAG_MODI_T_GIS     NUMBER(1),
  FLAG_MODI_P_GIS     NUMBER(1),
  SUPE_CATA           NUMBER(8),
  FLAG_STATO_CATA     VARCHAR2(1 BYTE),
  FOGLIOAU            NUMBER(4)
)
TABLESPACE SITIPIOPR_TBL
;

CREATE INDEX IE1_QGIS_W_SITIPLAV ON QGIS_W_SITIPLAV
(ID_LAV, LAST)
TABLESPACE SITIPIOPR_IDX;

alter table QGIS_D_NOME_BATCH add DT_ULTIMA_ESECUZIONE_PREC date;	

CREATE TABLE SITISUOLO_ATTIVE_PULITE
(
  COD_NAZIONALE       CHAR(4 BYTE)              NOT NULL,
  FOGLIO              NUMBER(4)                 NOT NULL,
  PARTICELLA          CHAR(5 BYTE)              NOT NULL,
  SUB                 VARCHAR2(3 BYTE)          NOT NULL,
  PROG_POLIGONO       NUMBER(5)                 NOT NULL,
  DATA_FINE_VAL       DATE                      NOT NULL,
  ALLEGATO            CHAR(1 BYTE)              DEFAULT '0'                   NOT NULL,
  SVILUPPO            CHAR(1 BYTE)              DEFAULT '0'                   NOT NULL,
  CAMPAGNA            NUMBER(4)                 DEFAULT 2011,
  UTENTE              VARCHAR2(100 BYTE)        NOT NULL,
  DATA_INIZIO_VAL     DATE,
  DATA_LAV            DATE                      DEFAULT SYSDATE               NOT NULL,
  AREA_COLT           NUMBER(11,2),
  COD_COLTURA         NUMBER(3),
  SHAPE               MDSYS.SDO_GEOMETRY,
  ANNO_FOTO           NUMBER(4),
  MESE_FOTO           NUMBER(2),
  SE_ROW_ID           NUMBER(10)                NOT NULL,
  COD_VARIETA         NUMBER(5),
  TARA                NUMBER(11,2),
  ISTATP              NUMBER(3),
  COD_UTIL            NUMBER(3),
  STATO_COLT          NUMBER(2),
  STATO_PROP          NUMBER(1)                 DEFAULT 0,
  UTENTE_FINE         VARCHAR2(100 BYTE),
  UTENTE_PROP         VARCHAR2(100 BYTE),
  UTENTE_PROP_FINE    VARCHAR2(100 BYTE),
  ID_TRASF            NUMBER(9)                 DEFAULT 0,
  ID_TRASF_FINE       NUMBER(9)                 DEFAULT 0,
  SORGENTE            NUMBER(9),
  VALI_PROD           NUMBER(1),
  TAVOLA              NUMBER(4),
  FLAGCARICO          NUMBER(9),
  DATA_AGGIORNAMENTO  DATE,
  GRUPPO              NUMBER(9),
  ID_PARTICELLA       NUMBER(9),
  IDFOTO              NUMBER(9),
  DXFOTO              NUMBER(3),
  DYFOTO              NUMBER(3),
  ALMOST_DEAD         NUMBER,
  FLAG_PROVENIENZA    VARCHAR2(1 BYTE),
  SYNC_SV_ID          NUMBER(9),
  ID_CONTROLLO        NUMBER(9)
)	
COLUMN SHAPE NOT SUBSTITUTABLE AT ALL LEVELS
VARRAY "SHAPE"."SDO_ELEM_INFO" STORE AS LOB (tablespace SITIPIOPR_lob)
VARRAY "SHAPE"."SDO_ORDINATES" STORE AS LOB (tablespace SITIPIOPR_lob)
TABLESPACE SITIPIOPR_TBL;


INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
VALUES(
	'SITISUOLO_ATTIVE_PULITE', 
	'SHAPE',
	SDO_DIM_ARRAY(
		SDO_DIM_ELEMENT ('X', 1310000, 2820000, 0.005),
		SDO_DIM_ELEMENT ('Y', 3930000, 5220000, 0.005)
	),
	NULL
);

ALTER TABLE QGIS_T_PARTICELLA_LAVORAZIONE 
    MODIFY ( DESCRIZIONE_SOSPENSIONE NULL ) 
;


ALTER TABLE QGIS_T_PARTICELLA_LAVORAZIONE ADD 
    ( 
     EXT_ID_PARTICELLA NUMBER (10) 
    ) 
;


ALTER TABLE QGIS_T_PARTICELLA_LAVORAZIONE ADD 
    ( 
     EXT_COD_NAZIONALE VARCHAR2 (4) 
    ) 
;


ALTER TABLE QGIS_T_PARTICELLA_LAVORAZIONE ADD 
    ( 
     FOGLIO NUMBER (4) 
    ) 
;


ALTER TABLE QGIS_T_PARTICELLA_LAVORAZIONE ADD 
    ( 
     PARTICELLA VARCHAR2 (5) 
    ) 
;


ALTER TABLE QGIS_T_PARTICELLA_LAVORAZIONE ADD 
    ( 
     SUBALTERNO VARCHAR2 (3) 
    ) 
;

commit;

CREATE INDEX IE1_SITISUOLO_ATTIVE_PULITE ON SITISUOLO_ATTIVE_PULITE
(COD_NAZIONALE)
TABLESPACE SITIPIOPR_IDX;

CREATE OR REPLACE FUNCTION get_data_gis_campagna (
      in_cod_nazionale      IN   VARCHAR2,
      in_foglio             IN   NUMBER,
      in_particella         IN   VARCHAR2,
      in_sub                IN   VARCHAR2,
      in_anno_riferimento   IN   INTEGER
   )
      RETURN DATE
   IS
      retvalue   DATE;
   BEGIN
      begin
      SELECT data_fine_val
           INTO retvalue
           FROM (SELECT   campagna, data_fine_val
                     FROM sitisuolo
                    WHERE cod_nazionale = in_cod_nazionale
                      AND foglio = in_foglio
                      AND particella = in_particella
                      AND sub = in_sub
                      AND campagna <= in_anno_riferimento
                 ORDER BY campagna DESC, data_fine_val DESC)
          WHERE ROWNUM = 1;
      EXCEPTION
         WHEN NO_DATA_FOUND
         THEN
            retvalue := to_date('31/12/9999','dd/mm/yyyy');
      END;
      
      return retvalue;
end get_data_gis_campagna;
/

CREATE OR REPLACE TYPE obj_Suoli AS object(
CAMPAGNA NUMBER(4),
AREA_COLT NUMBER(11,2),
DATA_FINE_VALIDITA DATE,
COD_VARIETA VARCHAR2(10),
ID_TIPO_SORGENTE_SUOLO NUMBER(4),
EXT_ID_UTENTE_AGGIORNAMENTO NUMBER(10),
SHAPE SDO_GEOMETRY,
EXT_ID_UTENTE_LAVOR_SITICLIENT VARCHAR2(100),
SE_ROW_ID  NUMBER(10));
/

CREATE OR REPLACE TYPE  list_Suoli AS TABLE OF obj_Suoli;
/

grant execute on obj_Suoli to smrgaa;
grant execute on list_Suoli to smrgaa;

-- Script grants
declare
  
  Procedure CreateGrantToUser is
  TYPE tpUser IS RECORD (nomeUser  VARCHAR2(30),
  	   		   		     Comando   VARCHAR2(300));
						   
  TYPE typTbUser IS TABLE OF tpUser INDEX BY BINARY_INTEGER;						   
  
  tUser    typTbUser;
  
  begin
    tUser(1).nomeUser := 'SITIPIOPR_RW';
    tUser(1).comando  := 'grant select,insert, update, delete on ';
	
	FOR i IN tUser.FIRST..tUser.LAST LOOP
	--grant sulle tabelle
    for c in ( 
       select tUser(i).comando||tb.table_name||' to '||tUser(i).nomeUser cmd from user_tables tb where tb.table_name != 'DBG_GATE_CALLS'
    ) loop
      execute immediate c.cmd;
    end loop;

    -- Grant sulle sequence
    for c in ( 
       select 'grant select,alter on '||se.sequence_name||' to '||tUser(i).nomeUser cmd from user_sequences se
    ) loop 
      execute immediate c.cmd;
    end loop;

    -- Grant su Procedure/Funzioni/Package
    for c in ( 
       select distinct 'grant execute on '||pr.object_name||' to '||tUser(i).nomeUser cmd from user_procedures pr 
    ) loop
      execute immediate c.cmd;
    end loop;
	
	-- Grant su types
    for c in ( 
       select distinct 'grant execute on '||pr.type_name||' to '||tUser(i).nomeUser cmd from user_types pr where instr(pr.type_name,'SYS') = 0 
    ) loop
      execute immediate c.cmd;
    end loop;
	
	-- Grant su viste
    for c in ( 
       select distinct 'grant select on '||vi.view_name||' to '||tUser(i).nomeUser cmd from user_views vi 
    ) loop
      execute immediate c.cmd;
    end loop;
    
    end loop;
  end;                           
begin
  CreateGrantToUser;
end;
/


	

